// Complete Vocabulary for Lessons 5 to 9 from 『できる日本語 初中級 本冊』
window.VOCABULARY_PART2 = [
  // LESSON 5: 大変な1日 (A Tough Day)
  { id: 250, lesson: 5, kanji: "失敗・する", furigana: "しっぱいする", romaji: "shippai suru", en: "fail, make a mistake", bn: "ভুল করা / ব্যর্থ হওয়া" },
  { id: 251, lesson: 5, kanji: "池", furigana: "いけ", romaji: "ike", en: "pond", bn: "পুকুর" },
  { id: 252, lesson: 5, kanji: "色", furigana: "いろ", romaji: "iro", en: "color", bn: "রঙ" },
  { id: 253, lesson: 5, kanji: "ピンク", furigana: "ピンク", romaji: "pinku", en: "pink", bn: "গোলাপি" },
  { id: 254, lesson: 5, kanji: "緑", furigana: "みどり", romaji: "midori", en: "green", bn: "সবুজ" },
  { id: 255, lesson: 5, kanji: "駅員", furigana: "えきいん", romaji: "ekiin", en: "station employee", bn: "রেলওয়ে স্টেশন কর্মী" },
  { id: 256, lesson: 5, kanji: "警官", furigana: "けいかん", romaji: "keikan", en: "policeman", bn: "পুলিশ কর্মকর্তা" },
  { id: 257, lesson: 5, kanji: "大きさ", furigana: "おおきさ", romaji: "ookisa", en: "size", bn: "আকার / সাইজ" },
  { id: 258, lesson: 5, kanji: "カード", furigana: "カード", romaji: "kaado", en: "card", bn: "কার্ড" },
  { id: 259, lesson: 5, kanji: "財布にカードが入っている", furigana: "さいふにカードがはいっている", romaji: "saifu ni kaado ga haitte iru", en: "The card is in my wallet", bn: "মানিব্যাগে কার্ড আছে" },
  { id: 260, lesson: 5, kanji: "階段", furigana: "かいだん", romaji: "kaidan", en: "stairs", bn: "সিঁড়ি" },
  { id: 261, lesson: 5, kanji: "鍵", furigana: "かぎ", romaji: "kagi", en: "key", bn: "চাবি" },
  { id: 262, lesson: 5, kanji: "形", furigana: "かたち", romaji: "katachi", en: "shape", bn: "আকৃতি" },
  { id: 263, lesson: 5, kanji: "ハート", furigana: "ハート", romaji: "haato", en: "heart", bn: "হৃদয় / হার্ট" },
  { id: 264, lesson: 5, kanji: "星", furigana: "ほし", romaji: "hoshi", en: "star", bn: "তারা / নক্ষত্র" },
  { id: 265, lesson: 5, kanji: "革", furigana: "かわ", romaji: "kawa", en: "leather", bn: "চামড়া" },
  { id: 266, lesson: 5, kanji: "切符", furigana: "きっぷ", romaji: "kippu", en: "ticket", bn: "টিকিট" },
  { id: 267, lesson: 5, kanji: "教科書", furigana: "きょうかしょ", romaji: "kyoukasho", en: "textbook", bn: "পাঠ্যবই" },
  { id: 268, lesson: 5, kanji: "ケース", furigana: "ケース", romaji: "keesu", en: "case", bn: "খাপ / কেস" },
  { id: 269, lesson: 5, kanji: "線路", furigana: "せんろ", romaji: "senro", en: "railway / subway line", bn: "রেললাইন" },
  { id: 270, lesson: 5, kanji: "途中", furigana: "とちゅう", romaji: "tochuu", en: "in the middle of doing something", bn: "পথিমধ্যে / মাঝামাঝি" },
  { id: 271, lesson: 5, kanji: "窓口", furigana: "まどぐち", romaji: "madoguchi", en: "ticket counter", bn: "কাউন্টার" },
  { id: 272, lesson: 5, kanji: "横長", furigana: "よこなが", romaji: "yokonaga", en: "long from side to side", bn: "চওড়া / অনুভূমিক লম্বা" },
  { id: 273, lesson: 5, kanji: "忘れ物", furigana: "わすれもの", romaji: "wasuremono", en: "lost items, lost-and-found", bn: "হারিয়ে যাওয়া জিনিস" },
  { id: 274, lesson: 5, kanji: "ICカード", furigana: "アイシーカード", romaji: "aishiikaado", en: "IC card, smart card", bn: "আইসি কার্ড / স্মার্ট কার্ড" },
  { id: 275, lesson: 5, kanji: "～辺（どの辺）", furigana: "～へん（どのへん）", romaji: "~hen (dono hen)", en: "somewhere around ~, Whereabouts?", bn: "আশপাশ (কোন আশপাশে?)" },
  { id: 276, lesson: 5, kanji: "落とす", furigana: "おとす", romaji: "otosu", en: "drop, lose", bn: "ফেলে দেওয়া / হারানো" },
  { id: 277, lesson: 5, kanji: "困る", furigana: "こまる", romaji: "komaru", en: "be in trouble", bn: "বিপদে পড়া" },
  { id: 278, lesson: 5, kanji: "転ぶ", furigana: "ころぶ", romaji: "korobu", en: "fall down", bn: "আছাড় খাওয়া / পড়ে যাওয়া" },
  { id: 279, lesson: 5, kanji: "壊す", furigana: "こわす", romaji: "kowasu", en: "break, destroy", bn: "ভেঙে ফেলা" },
  { id: 280, lesson: 5, kanji: "付く", furigana: "つく", romaji: "tsuku", en: "attach", bn: "লেগে থাকা / যুক্ত হওয়া" },
  { id: 281, lesson: 5, kanji: "ポケットが付いている", furigana: "ポケットがついている", romaji: "poketto ga tsuite iru", en: "A pocket is attached", bn: "পকেট লাগানো আছে" },
  { id: 282, lesson: 5, kanji: "なくなる", furigana: "なくなる", romaji: "nakunaru", en: "lose (something), disappear", bn: "হারিয়ে যাওয়া" },
  { id: 283, lesson: 5, kanji: "自転車がなくなった", furigana: "じてんしゃがなくなった", romaji: "jitensha ga nakunatta", en: "I lost my bicycle", bn: "সাইকেলটি হারিয়ে গেছে" },
  { id: 284, lesson: 5, kanji: "乗り過ごす", furigana: "のりすごす", romaji: "norisugosu", en: "miss one's stop", bn: "স্টেশন ফেলে সামনে চলে যাওয়া" },
  { id: 285, lesson: 5, kanji: "迷う", furigana: "まよう", romaji: "mayou", en: "lose one's way, hesitate", bn: "পথ হারানো / দ্বিধা করা" },
  { id: 286, lesson: 5, kanji: "道に迷う", furigana: "みちにまよう", romaji: "michi ni mayou", en: "get lost", bn: "রাস্তা হারিয়ে ফেলা" },
  { id: 287, lesson: 5, kanji: "見つかる", furigana: "みつかる", romaji: "mitsukaru", en: "find, be found", bn: "খুঁজে পাওয়া যাওয়া" },
  { id: 288, lesson: 5, kanji: "出る", furigana: "でる", romaji: "deru", en: "leave, exit", bn: "বের হওয়া" },
  { id: 289, lesson: 5, kanji: "駅を出る", furigana: "えきをでる", romaji: "eki o deru", en: "leave a station", bn: "স্টেশন থেকে বের হওয়া" },
  { id: 290, lesson: 5, kanji: "乗り換える", furigana: "のりかえる", romaji: "norikaeru", en: "change (trains, planes)", bn: "গাড়ি বা ট্রেন বদলানো" },
  { id: 291, lesson: 5, kanji: "間違える", furigana: "まちがえる", romaji: "machigaeru", en: "make a mistake", bn: "ভুল করা" },
  { id: 292, lesson: 5, kanji: "心配・する", furigana: "しんぱいする", romaji: "shinpai suru", en: "worry", bn: "চিন্তা করা" },
  { id: 293, lesson: 5, kanji: "連絡・する", furigana: "れんらくする", romaji: "renraku suru", en: "contact, get in touch", bn: "যোগাযোগ করা" },
  { id: 294, lesson: 5, kanji: "気がつく", furigana: "きがつく", romaji: "ki ga tsuku", en: "notice, realize", bn: "খেয়াল করা / টের পাওয়া" },
  { id: 295, lesson: 5, kanji: "急に", furigana: "きゅうに", romaji: "kyuu ni", en: "suddenly", bn: "হঠাৎ করে" },
  { id: 296, lesson: 5, kanji: "さっき", furigana: "さっき", romaji: "sakki", en: "a moment ago", bn: "কিছুক্ষণ আগে" },
  { id: 297, lesson: 5, kanji: "しばらく", furigana: "しばらく", romaji: "shibaraku", en: "in a little while, for a while", bn: "কিছুক্ষণ / অল্প সময়ের জন্য" },
  { id: 298, lesson: 5, kanji: "全部で", furigana: "ぜんぶで", romaji: "zenbu de", en: "altogether", bn: "সব মিলিয়ে" },
  { id: 299, lesson: 5, kanji: "確かに", furigana: "たしかに", romaji: "tashika ni", en: "I am certain that, surely", bn: "নিশ্চিতভাবেই" },
  { id: 300, lesson: 5, kanji: "それが……", furigana: "それが……", romaji: "sore ga...", en: "That is ...", bn: "আসলে কথাটা হলো..." },
  { id: 301, lesson: 5, kanji: "どうしよう", furigana: "どうしよう", romaji: "doushiyou", en: "What should I do?", bn: "এখন কী করব?" },
  { id: 302, lesson: 5, kanji: "急行", furigana: "きゅうこう", romaji: "kyuukou", en: "express train", bn: "এক্সপ্রেস ট্রেন" },
  { id: 303, lesson: 5, kanji: "特急", furigana: "とっきゅう", romaji: "tokkyuu", en: "limited express train", bn: "বিশেষ দ্রুতগামী ট্রেন" },
  { id: 304, lesson: 5, kanji: "コインロッカー", furigana: "コインロッカー", romaji: "koinrokkaa", en: "coin locker", bn: "কয়েন লকার" },
  { id: 305, lesson: 5, kanji: "終点", furigana: "しゅうてん", romaji: "shuuten", en: "final stop", bn: "শেষ স্টেশন / অন্তিম গন্তব্য" },
  { id: 306, lesson: 5, kanji: "終電", furigana: "しゅうでん", romaji: "shuuden", en: "final train of the day", bn: "দিনের শেষ ট্রেন" },
  { id: 307, lesson: 5, kanji: "タクシー", furigana: "タクシー", romaji: "takushii", en: "taxi", bn: "ট্যাক্সি" },
  { id: 308, lesson: 5, kanji: "定期券", furigana: "ていきけん", romaji: "teikiken", en: "commuter pass", bn: "যাত্রী পাস / ট্রেন পাস" },
  { id: 309, lesson: 5, kanji: "箱", furigana: "はこ", romaji: "hako", en: "box", bn: "বাক্স" },
  { id: 310, lesson: 5, kanji: "文字", furigana: "もじ", romaji: "moji", en: "character, letter", bn: "অক্ষর / বর্ণ" },
  { id: 311, lesson: 5, kanji: "～点（100点）", furigana: "～てん（ひゃくてん）", romaji: "~ten (hyakuten)", en: "point(s) (e.g. 100 points)", bn: "পয়েন্ট / নম্বর (১০০ নম্বর)" },
  { id: 312, lesson: 5, kanji: "預かる", furigana: "あずかる", romaji: "azukaru", en: "leave in someone's care, check in", bn: "জিম্মায় রাখা / জমা রাখা" },
  { id: 313, lesson: 5, kanji: "取る", furigana: "とる", romaji: "toru", en: "take, get", bn: "নেওয়া / পাওয়া" },
  { id: 314, lesson: 5, kanji: "100点を取る", furigana: "ひゃくてんをとる", romaji: "hyakuten o toru", en: "get 100 points", bn: "১০০ নম্বর পাওয়া" },
  { id: 315, lesson: 5, kanji: "戻る", furigana: "もどる", romaji: "modoru", en: "return", bn: "ফিরে আসা" },
  { id: 316, lesson: 5, kanji: "変える", furigana: "かえる", romaji: "kaeru", en: "change", bn: "পরিবর্তন করা" },
  { id: 317, lesson: 5, kanji: "アナウンス・する", furigana: "アナウンスする", romaji: "anaunsu suru", en: "announce", bn: "ঘোষণা দেওয়া" },
  { id: 318, lesson: 5, kanji: "安心・する", furigana: "あんしんする", romaji: "anshin suru", en: "relieve, give peace of mind", bn: "স্বস্তি পাওয়া / নিশ্চিন্ত হওয়া" },
  { id: 319, lesson: 5, kanji: "遅刻・する", furigana: "ちこくする", romaji: "chikoku suru", en: "be late", bn: "দেরি করা" },
  { id: 320, lesson: 5, kanji: "寝坊・する", furigana: "ねぼうする", romaji: "nebou suru", en: "sleep late, oversleep", bn: "দেরিতে ঘুম থেকে ওঠা" },
  { id: 321, lesson: 5, kanji: "びっくり・する", furigana: "びっくりする", romaji: "bikkuri suru", en: "be surprised", bn: "চমকে যাওয়া / অবাক হওয়া" },
  { id: 322, lesson: 5, kanji: "薄い", furigana: "うすい", romaji: "usui", en: "thin, weak, faint", bn: "হালকা / পাতলা" },
  { id: 323, lesson: 5, kanji: "この料理は味が薄い", furigana: "このりょうりはあじがうすい", romaji: "kono ryouri wa aji ga usui", en: "This cooking has a weak flavor", bn: "এই খাবারের স্বাদ হালকা" },
  { id: 324, lesson: 5, kanji: "すぐ", furigana: "すぐ", romaji: "sugu", en: "immediately", bn: "তৎক্ষণাৎ / সাথে সাথে" },
  { id: 325, lesson: 5, kanji: "本当に", furigana: "ほんとうに", romaji: "hontou ni", en: "really, truly", bn: "সত্যিই" },
  { id: 326, lesson: 5, kanji: "もう少し", furigana: "もうすこし", romaji: "mou sukoshi", en: "a little more", bn: "আর একটু" },
  { id: 327, lesson: 5, kanji: "ゆっくり", furigana: "ゆっくり", romaji: "yukkuri", en: "slowly", bn: "ধীরে ধীরে" },
  { id: 328, lesson: 5, kanji: "ゆっくり話してください", furigana: "ゆっくりはなしてください", romaji: "yukkuri hanashite kudasai", en: "Please speak slowly", bn: "অনুগ্রহ করে আস্তে কথা বলুন" },
  { id: 329, lesson: 5, kanji: "白", furigana: "しろ", romaji: "shiro", en: "white", bn: "সাদা" },
  { id: 330, lesson: 5, kanji: "～号車", furigana: "～ごうしゃ", romaji: "~gousha", en: "number ~ train car", bn: "নম্বর বগি / কামরা" },
  { id: 331, lesson: 5, kanji: "～ずつ", furigana: "～ずつ", romaji: "~zutsu", en: "every ~, each", bn: "করে / প্রতিটি" },

  // LESSON 6: 旅行に行こう (Let's Go on a Trip)
  { id: 332, lesson: 6, kanji: "ウニ", furigana: "ウニ", romaji: "uni", en: "sea urchin", bn: "সামুদ্রিক প্রাণী ইউনি" },
  { id: 333, lesson: 6, kanji: "カヌー", furigana: "カヌー", romaji: "kanuu", en: "canoe", bn: "ক্যানো নৌকা" },
  { id: 334, lesson: 6, kanji: "自然", furigana: "しぜん", romaji: "shizen", en: "nature", bn: "প্রকৃতি" },
  { id: 335, lesson: 6, kanji: "湿原", furigana: "しつげん", romaji: "shitsugen", en: "marsh, wetland", bn: "জলাভূমি" },
  { id: 336, lesson: 6, kanji: "ジャガイモ", furigana: "ジャガイモ", romaji: "jagaimo", en: "potato", bn: "আলু" },
  { id: 337, lesson: 6, kanji: "乗馬", furigana: "じょうば", romaji: "jouba", en: "horseback riding", bn: "ঘোড়ায় চড়া" },
  { id: 338, lesson: 6, kanji: "トウモロコシ", furigana: "トウモロコシ", romaji: "toumorokoshi", en: "corn, maize", bn: "ভুট্টা" },
  { id: 339, lesson: 6, kanji: "牧場", furigana: "ぼくじょう", romaji: "bokujou", en: "ranch, farm", bn: "খামার / পশুপালন কেন্দ্র" },
  { id: 340, lesson: 6, kanji: "ラベンダー畑", furigana: "ラベンダーばたけ", romaji: "rabendaa batake", en: "Lavender Farm", bn: "ল্যাভেন্ডার ফুলের বাগান" },
  { id: 341, lesson: 6, kanji: "楽しむ", furigana: "たのしむ", romaji: "tanoshimu", en: "enjoy", bn: "উপভোগ করা" },
  { id: 342, lesson: 6, kanji: "大人", furigana: "おとな", romaji: "otona", en: "adult", bn: "প্রাপ্তবয়স্ক" },
  { id: 343, lesson: 6, kanji: "カニ", furigana: "カニ", romaji: "kani", en: "crab", bn: "কাঁকড়া" },
  { id: 344, lesson: 6, kanji: "着物", furigana: "きもの", romaji: "kimono", en: "clothing, kimono", bn: "কিমোনো / ঐতিহ্যবাহী পোশাক" },
  { id: 345, lesson: 6, kanji: "こっち", furigana: "こっち", romaji: "kocchi", en: "this way (informal)", bn: "এদিকে (ঘরোয়া)" },
  { id: 346, lesson: 6, kanji: "そっち", furigana: "そっち", romaji: "socchi", en: "that way (informal)", bn: "ওদিকে (ঘরোয়া)" },
  { id: 347, lesson: 6, kanji: "最後", furigana: "さいご", romaji: "saigo", en: "last, final", bn: "শেষ / সমাপ্তি" },
  { id: 348, lesson: 6, kanji: "市内", furigana: "しない", romaji: "shinai", en: "within the city", bn: "শহরের ভেতরে" },
  { id: 349, lesson: 6, kanji: "ショッピングセンター", furigana: "ショッピングセンター", romaji: "shoppingu sentaa", en: "shopping center, mall", bn: "শপিং সেন্টার" },
  { id: 350, lesson: 6, kanji: "宿泊", furigana: "しゅくはく", romaji: "shukuhaku", en: "lodging, stay", bn: "রাত্রিযাপন / থাকা" },
  { id: 351, lesson: 6, kanji: "水族館", furigana: "すいぞくかん", romaji: "suizokukan", en: "aquarium", bn: "অ্যাকোয়ারিয়াম" },
  { id: 352, lesson: 6, kanji: "スノーボード", furigana: "スノーボード", romaji: "sunooboodo", en: "snowboard", bn: "স্নোবোর্ড" },
  { id: 353, lesson: 6, kanji: "代金", furigana: "だいきん", romaji: "daikin", en: "charges, fees", bn: "মূল্য / ভাড়া" },
  { id: 354, lesson: 6, kanji: "朝食", furigana: "ちょうしょく", romaji: "choushoku", en: "breakfast", bn: "সকালের নাস্তা" },
  { id: 355, lesson: 6, kanji: "夕食", furigana: "ゆうしょく", romaji: "yuushoku", en: "dinner", bn: "রাতের খাবার" },
  { id: 356, lesson: 6, kanji: "登山", furigana: "とざん", romaji: "tozan", en: "mountain climbing", bn: "পর্বতারোহণ" },
  { id: 357, lesson: 6, kanji: "内容", furigana: "ないよう", romaji: "naiyou", en: "details, content", bn: "বিষয়বস্তু" },
  { id: 358, lesson: 6, kanji: "なし", furigana: "なし", romaji: "nashi", en: "none, without", bn: "নেই / ছাড়া" },
  { id: 359, lesson: 6, kanji: "値段", furigana: "ねだん", romaji: "nedan", en: "price", bn: "দাম / মূল্য" },
  { id: 360, lesson: 6, kanji: "船", furigana: "ふね", romaji: "fune", en: "ship, boat", bn: "জাহাজ / নৌকা" },
  { id: 361, lesson: 6, kanji: "プラン", furigana: "プラン", romaji: "puran", en: "plan, package", bn: "পরিকল্পনা / প্যাকেজ" },
  { id: 362, lesson: 6, kanji: "雰囲気", furigana: "ふんいき", romaji: "fun'iki", en: "atmosphere, mood", bn: "পরিবেশ / আবহ" },
  { id: 363, lesson: 6, kanji: "街", furigana: "まち", romaji: "machi", en: "town, city street", bn: "শহর / জনপদ" },
  { id: 364, lesson: 6, kanji: "虫", furigana: "むし", romaji: "mushi", en: "bugs, insects", bn: "পোকামাকড়" },
  { id: 365, lesson: 6, kanji: "旅館", furigana: "りょかん", romaji: "ryokan", en: "Japanese-style inn", bn: "জাপানি ঐতিহ্যবাহী হোটেল" },
  { id: 366, lesson: 6, kanji: "～付き（朝食付き）", furigana: "～つき（ちょうしょくつき）", romaji: "~tsuki (choushokutsuki)", en: "included (e.g. breakfast included)", bn: "সহ (সকালের নাস্তাসহ)" },
  { id: 367, lesson: 6, kanji: "～泊～日（2泊3日）", furigana: "～はく～か（にはくみっか）", romaji: "~haku ~ka (nihakumikka)", en: "~ nights ~ days (2 nights 3 days)", bn: "রাত ও দিন (২ রাত ৩ দিন)" },
  { id: 368, lesson: 6, kanji: "～費（交通費）", furigana: "～ひ（こうつうひ）", romaji: "~hi (koutsuuhi)", en: "~ fee (transportation fee)", bn: "খরচ (যাতায়াত খরচ)" },
  { id: 369, lesson: 6, kanji: "どっち", furigana: "どっち", romaji: "docchi", en: "which", bn: "কোনটি" },
  { id: 370, lesson: 6, kanji: "待ち合わせる", furigana: "まちあわせる", romaji: "machiawaseru", en: "meet with", bn: "দেখা করার জন্য অপেক্ষা করা" },
  { id: 371, lesson: 6, kanji: "ガイド・する", furigana: "ガイドする", romaji: "gaido suru", en: "guide", bn: "পথ দেখানো / গাইড করা" },
  { id: 372, lesson: 6, kanji: "観光・する", furigana: "かんこうする", romaji: "kankou suru", en: "go sightseeing, tour", bn: "দর্শনীয় স্থান ঘোরা" },
  { id: 373, lesson: 6, kanji: "キャンプ・する", furigana: "キャンプする", romaji: "kyanpu suru", en: "camp", bn: "ক্যাম্পিং করা" },
  { id: 374, lesson: 6, kanji: "出発・する", furigana: "しゅっぱつする", romaji: "shuppatsu suru", en: "leave, depart", bn: "রওয়ানা হওয়া" },
  { id: 375, lesson: 6, kanji: "チェックイン・する", furigana: "チェックインする", romaji: "chekkuin suru", en: "check in (at a hotel)", bn: "হোটেল চেক-ইন করা" },
  { id: 376, lesson: 6, kanji: "レンタル・する", furigana: "レンタルする", romaji: "rentaru suru", en: "rent (car, office, etc.)", bn: "ভাড়া নেওয়া" },
  { id: 377, lesson: 6, kanji: "珍しい", furigana: "めずらしい", romaji: "mezurashii", en: "unusual, rare", bn: "বিরল / দুর্লভ" },
  { id: 378, lesson: 6, kanji: "伝統的（な）", furigana: "でんとうてき（な）", romaji: "dentouteki (na)", en: "traditional", bn: "ঐতিহ্যবাহী" },
  { id: 379, lesson: 6, kanji: "それに", furigana: "それに", romaji: "sore ni", en: "also, in addition", bn: "তাছাড়া / আরও" },
  { id: 380, lesson: 6, kanji: "イルカ", furigana: "イルカ", romaji: "iruka", en: "dolphin", bn: "ডলফিন" },
  { id: 381, lesson: 6, kanji: "ガイドブック", furigana: "ガイドブック", romaji: "gaidobukku", en: "guidebook", bn: "ভ্রমণ গাইড বই" },
  { id: 382, lesson: 6, kanji: "ショー", furigana: "ショー", romaji: "shoo", en: "show", bn: "প্রদর্শনী" },
  { id: 383, lesson: 6, kanji: "手袋", furigana: "てぶくろ", romaji: "tebukuro", en: "gloves", bn: "হাতমোজা" },
  { id: 384, lesson: 6, kanji: "年末", furigana: "ねんまつ", romaji: "nenmatsu", en: "end of year", bn: "বছরের শেষ সময়" },
  { id: 385, lesson: 6, kanji: "マフラー", furigana: "マフラー", romaji: "mafuraa", en: "scarf, muffler", bn: "মাফলার" },
  { id: 386, lesson: 6, kanji: "～中（旅行中）", furigana: "～ちゅう（りょこうちゅう）", romaji: "~chuu (ryokouchuu)", en: "during ~ (during travel)", bn: "চলাকালীন (ভ্রমণকালীন)" },
  { id: 387, lesson: 6, kanji: "取る", furigana: "とる", romaji: "toru", en: "take", bn: "নেওয়া" },
  { id: 388, lesson: 6, kanji: "休みを取る", furigana: "やすみをとる", romaji: "yasumi o toru", en: "take a vacation", bn: "ছুটি নেওয়া" },
  { id: 389, lesson: 6, kanji: "なくなる", furigana: "なくなる", romaji: "nakunaru", en: "run out, disappear, be missing", bn: "শেষ হয়ে যাওয়া" },
  { id: 390, lesson: 6, kanji: "席がなくなる", furigana: "せきがなくなる", romaji: "seki ga nakunaru", en: "There are no more seats left", bn: "সিট ফুরিয়ে গেছে" },
  { id: 391, lesson: 6, kanji: "伝える", furigana: "つたえる", romaji: "tsutaeru", en: "tell (someone something)", bn: "জানানো / বার্তা দেওয়া" },
  { id: 392, lesson: 6, kanji: "ぬれる", furigana: "ぬれる", romaji: "nureru", en: "get wet", bn: "ভিজে যাওয়া" },
  { id: 393, lesson: 6, kanji: "コピー・する", furigana: "コピーする", romaji: "kopii suru", en: "make a photocopy", bn: "ফটোকপি করা" },
  { id: 394, lesson: 6, kanji: "到着・する", furigana: "とうちゃくする", romaji: "touchaku suru", en: "to arrive", bn: "পৌঁছানো" },
  { id: 395, lesson: 6, kanji: "用意・する", furigana: "よういする", romaji: "youi suru", en: "prepare", bn: "প্রস্তুত করা" },
  { id: 396, lesson: 6, kanji: "お願いします", furigana: "おねがいします", romaji: "onegai shimasu", en: "\"Please (do it)\"", bn: "অনুগ্রহ করে করুন" },
  { id: 397, lesson: 6, kanji: "あとで", furigana: "あとで", romaji: "ato de", en: "later", bn: "পরে" },

  // LESSON 7: 西川さんの家へ (To Mr. Nishikawa's House)
  { id: 398, lesson: 7, kanji: "相手", furigana: "あいて", romaji: "aite", en: "the other person", bn: "অপর পক্ষ / সামনের জন" },
  { id: 399, lesson: 7, kanji: "習慣", furigana: "しゅうかん", romaji: "shuukan", en: "custom, tradition, habit", bn: "প্রথা / ঐতিহ্য" },
  { id: 400, lesson: 7, kanji: "違い", furigana: "ちがい", romaji: "chigai", en: "difference", bn: "পার্থক্য" },
  { id: 401, lesson: 7, kanji: "驚く", furigana: "おどろく", romaji: "odoroku", en: "surprise, be surprised", bn: "অবাক হওয়া" },
  { id: 402, lesson: 7, kanji: "失礼（な）", furigana: "しつれい（な）", romaji: "shitsurei (na)", en: "rude, impolite", bn: "অভদ্র / বেয়াদব" },
  { id: 403, lesson: 7, kanji: "もう一度", furigana: "もういちど", romaji: "mou ichido", en: "one more time, again", bn: "আর একবার" },
  { id: 404, lesson: 7, kanji: "会議", furigana: "かいぎ", romaji: "kaigi", en: "conference, meeting", bn: "সভা / মিটিং" },
  { id: 405, lesson: 7, kanji: "課長", furigana: "かちょう", romaji: "kachou", en: "section chief", bn: "বিভাগীয় প্রধান" },
  { id: 406, lesson: 7, kanji: "社長", furigana: "しゃちょう", romaji: "shachou", en: "company president", bn: "কোম্পানির সভাপতি" },
  { id: 407, lesson: 7, kanji: "ご存じ", furigana: "ごぞんじ", romaji: "gozonji", en: "know (respectful language)", bn: "জানা (সম্মানসূচক)" },
  { id: 408, lesson: 7, kanji: "ミステリー", furigana: "ミステリー", romaji: "misuterii", en: "Mystery", bn: "রহস্য" },
  { id: 409, lesson: 7, kanji: "～頃（9時頃）", furigana: "～ごろ（くじごろ）", romaji: "~goro (kujigoro)", en: "around ~ (around 9:00)", bn: "কাছাকাছি সময় (৯টার দিকে)" },
  { id: 410, lesson: 7, kanji: "どなた", furigana: "どなた", romaji: "donata", en: "who (polite)", bn: "কে (ভদ্র রূপ)" },
  { id: 411, lesson: 7, kanji: "いらっしゃる", furigana: "いらっしゃる", romaji: "irassharu", en: "come, go, be (respectful language)", bn: "আসা / যাওয়া / থাকা (সম্মানসূচক)" },
  { id: 412, lesson: 7, kanji: "おっしゃる", furigana: "おっしゃる", romaji: "ossharu", en: "say (respectful language)", bn: "বলা (সম্মানসূচক)" },
  { id: 413, lesson: 7, kanji: "ご覧になる", furigana: "ごらんになる", romaji: "goran ni naru", en: "look at, see (respectful language)", bn: "দেখা (সম্মানসূচক)" },
  { id: 414, lesson: 7, kanji: "なさる", furigana: "なさる", romaji: "nasaru", en: "do (respectful language)", bn: "করা (সম্মানসূচক)" },
  { id: 415, lesson: 7, kanji: "召し上がる", furigana: "めしあがる", romaji: "meshiagaru", en: "eat, drink (respectful language)", bn: "খাওয়া / পান করা (সম্মানসূচক)" },
  { id: 416, lesson: 7, kanji: "出席・する", furigana: "しゅっせきする", romaji: "shusseki suru", en: "attend", bn: "উপস্থিত থাকা" },
  { id: 417, lesson: 7, kanji: "退院・する", furigana: "たいいんする", romaji: "taiin suru", en: "leave hospital, be discharged", bn: "হাসপাতাল থেকে ছাড়া পাওয়া" },
  { id: 418, lesson: 7, kanji: "味", furigana: "あじ", romaji: "aji", en: "taste, flavor", bn: "স্বাদ" },
  { id: 419, lesson: 7, kanji: "カップ", furigana: "カップ", romaji: "kappu", en: "cup", bn: "কাপ" },
  { id: 420, lesson: 7, kanji: "皮", furigana: "かわ", romaji: "kawa", en: "skin, peel", bn: "খোসা" },
  { id: 421, lesson: 7, kanji: "キャベツ", furigana: "キャベツ", romaji: "kyabetsu", en: "cabbage", bn: "বাঁধাকপি" },
  { id: 422, lesson: 7, kanji: "ジャガイモ", furigana: "ジャガイモ", romaji: "jagaimo", en: "potato", bn: "আলু" },
  { id: 423, lesson: 7, kanji: "大根", furigana: "だいこん", romaji: "daikon", en: "Japanese radish", bn: "জাপানি মূলা" },
  { id: 424, lesson: 7, kanji: "タマネギ", furigana: "タマネギ", romaji: "tamanegi", en: "onion", bn: "পেঁয়াজ" },
  { id: 425, lesson: 7, kanji: "ニンジン", furigana: "ニンジン", romaji: "ninjin", en: "carrot", bn: "গাজর" },
  { id: 426, lesson: 7, kanji: "ネギ", furigana: "ネギ", romaji: "negi", en: "green onion", bn: "পেঁয়াজ পাতা / কাঁচা পেঁয়াজ" },
  { id: 427, lesson: 7, kanji: "クリーム", furigana: "クリーム", romaji: "kuriimu", en: "cream", bn: "ক্রিম" },
  { id: 428, lesson: 7, kanji: "コショウ", furigana: "コショウ", romaji: "koshou", en: "black pepper", bn: "গোলমরিচ" },
  { id: 429, lesson: 7, kanji: "酢", furigana: "す", romaji: "su", en: "vinegar", bn: "সিরকা / ভিনেগার" },
  { id: 430, lesson: 7, kanji: "調味料", furigana: "ちょうみりょう", romaji: "choumiryou", en: "seasonings", bn: "রান্নার মশলা" },
  { id: 431, lesson: 7, kanji: "このくらい", furigana: "このくらい", romaji: "konokurai", en: "this much", bn: "এই পরিমাণ" },
  { id: 432, lesson: 7, kanji: "ゼリー", furigana: "ゼリー", romaji: "zerii", en: "jello, gelatin", bn: "জেলি" },
  { id: 433, lesson: 7, kanji: "ソース", furigana: "ソース", romaji: "soosu", en: "sauce", bn: "সস" },
  { id: 434, lesson: 7, kanji: "パスタのソースを作る", furigana: "パスタのソースをつくる", romaji: "pasuta no soosu o tsukuru", en: "make pasta sauce", bn: "পাস্তার সস তৈরি করা" },
  { id: 435, lesson: 7, kanji: "漬物", furigana: "つけもの", romaji: "tsukemono", en: "pickled vegetables", bn: "জাপানি আচার" },
  { id: 436, lesson: 7, kanji: "できあがり", furigana: "できあがり", romaji: "dekiagari", en: "finished, ready", bn: "তৈরি সম্পন্ন" },
  { id: 437, lesson: 7, kanji: "鍋", furigana: "なべ", romaji: "nabe", en: "pan, pot", bn: "রান্নার পাত্র / কড়াই" },
  { id: 438, lesson: 7, kanji: "パスタ", furigana: "パスタ", romaji: "pasuta", en: "pasta", bn: "পাস্তা" },
  { id: 439, lesson: 7, kanji: "ハチミツ", furigana: "ハチミツ", romaji: "hachimitsu", en: "honey", bn: "মধু" },
  { id: 440, lesson: 7, kanji: "火", furigana: "ひ", romaji: "hi", en: "heat, fire", bn: "আগুন / চুলার আঁচ" },
  { id: 441, lesson: 7, kanji: "強火", furigana: "つよび", romaji: "tsuyobi", en: "strong heat", bn: "তীব্র আঁচ" },
  { id: 442, lesson: 7, kanji: "弱火", furigana: "よわび", romaji: "yowabi", en: "low heat", bn: "মৃদু আঁচ" },
  { id: 443, lesson: 7, kanji: "半分", furigana: "はんぶん", romaji: "hanbun", en: "half", bn: "অর্ধেক" },
  { id: 444, lesson: 7, kanji: "みそ汁", furigana: "みそしる", romaji: "misoshiru", en: "miso soup", bn: "মিসো স্যুপ" },
  { id: 445, lesson: 7, kanji: "ルー", furigana: "ルー", romaji: "ruu", en: "roux (thickening agent)", bn: "স্যুপের ঘন মিশ্রণ (রু)" },
  { id: 446, lesson: 7, kanji: "ローリエ", furigana: "ローリエ", romaji: "roorie", en: "bay leaf", bn: "তেজপাতা" },
  { id: 447, lesson: 7, kanji: "～グラム", furigana: "～グラム", romaji: "~guramu", en: "~ gram", bn: "গ্রাম" },
  { id: 448, lesson: 7, kanji: "変わる", furigana: "かわる", romaji: "kawaru", en: "change", bn: "বদলানো / পরিবর্তিত হওয়া" },
  { id: 449, lesson: 7, kanji: "冷やす", furigana: "ひやす", romaji: "hiyasu", en: "cool", bn: "ঠান্ডা করা" },
  { id: 450, lesson: 7, kanji: "むく", furigana: "むく", romaji: "muku", en: "peel", bn: "খোসা ছাড়ানো" },
  { id: 451, lesson: 7, kanji: "焼く", furigana: "やく", romaji: "yaku", en: "fry, grill, bake, roast", bn: "ভাজা / সেঁকা" },
  { id: 452, lesson: 7, kanji: "沸かす", furigana: "わかす", romaji: "wakasu", en: "boil (water)", bn: "পানি ফোটানো" },
  { id: 453, lesson: 7, kanji: "炒める", furigana: "いためる", romaji: "itameru", en: "stir-fry", bn: "হালকা তেলে ভাজা" },
  { id: 454, lesson: 7, kanji: "煮る", furigana: "にる", romaji: "niru", en: "boil, simmer (food in water)", bn: "ঝোলে সেদ্ধ করা" },
  { id: 455, lesson: 7, kanji: "ゆでる", furigana: "ゆでる", romaji: "yuderu", en: "boil (vegetables, eggs in water)", bn: "পানিতে সেদ্ধ করা" },
  { id: 456, lesson: 7, kanji: "沸騰・する", furigana: "ふっとうする", romaji: "futtou suru", en: "bring to a boil", bn: "টগবগ করে ফোটা" },
  { id: 457, lesson: 7, kanji: "厚い", furigana: "あつい", romaji: "atsui", en: "thick", bn: "পুরু / মোটা" },
  { id: 458, lesson: 7, kanji: "薄い", furigana: "うすい", romaji: "usui", en: "thin, weak", bn: "পাতলা" },
  { id: 459, lesson: 7, kanji: "薄く切る", furigana: "うすくきる", romaji: "usuku kiru", en: "\"Cut thinly\"", bn: "পাতলা করে কাটা" },
  { id: 460, lesson: 7, kanji: "濃い", furigana: "こい", romaji: "koi", en: "dense, rich, thick", bn: "গাঢ় / কড়া" },
  { id: 461, lesson: 7, kanji: "細かい", furigana: "こまかい", romaji: "komakai", en: "fine, small", bn: "সূক্ষ্ম / কুচি কুচি" },
  { id: 462, lesson: 7, kanji: "細い", furigana: "ほそい", romaji: "hosoi", en: "narrow, thin", bn: "চিকন / সরু" },
  { id: 463, lesson: 7, kanji: "弱い", furigana: "よわい", romaji: "yowai", en: "weak", bn: "দুর্বল" },
  { id: 464, lesson: 7, kanji: "まず", furigana: "まず", romaji: "mazu", en: "at first", bn: "প্রথমে" },
  { id: 465, lesson: 7, kanji: "次に", furigana: "つぎに", romaji: "tsugi ni", en: "next", bn: "এরপর" },
  { id: 466, lesson: 7, kanji: "最後に", furigana: "さいごに", romaji: "saigo ni", en: "finally, lastly", bn: "সবশেষে" },
  { id: 467, lesson: 7, kanji: "肉じゃが", furigana: "にくじゃが", romaji: "nikujaga", en: "simmered meat and potatoes", bn: "নিকুজাগা (মাংস ও আলুর পদ)" },
  { id: 468, lesson: 7, kanji: "ラケット", furigana: "ラケット", romaji: "raketto", en: "racket", bn: "র‍্যাকেট" },
  { id: 469, lesson: 7, kanji: "遠慮・する", furigana: "えんりょする", romaji: "enryo suru", en: "refrain from, hesitate", bn: "সংকোচ করা / দ্বিধা করা" },
  { id: 470, lesson: 7, kanji: "だいたい", furigana: "だいたい", romaji: "daitai", en: "mostly, most of the time", bn: "মোটামুটি / প্রায়" },
  { id: 471, lesson: 7, kanji: "もちろん", furigana: "もちろん", romaji: "mochiron", en: "of course", bn: "অবশ্যই" },
  { id: 472, lesson: 7, kanji: "お邪魔します", furigana: "おじゃまします", romaji: "ojama shimasu", en: "excuse me for intruding", bn: "আপনাদের বিরক্ত করার জন্য মাফ করবেন" },
  { id: 473, lesson: 7, kanji: "よくいらっしゃいました", furigana: "よくいらっしゃいました", romaji: "yoku irasshaimashita", en: "thank you for coming", bn: "আপনার আগমন শুভ হোক" },

  // LESSON 8: ありがとう (Thank You)
  { id: 474, lesson: 8, kanji: "明るい", furigana: "あかるい", romaji: "akarui", en: "bright, cheerful", bn: "উজ্জ্বল / হাসিখুশি" },
  { id: 475, lesson: 8, kanji: "やっと", furigana: "やっと", romaji: "yatto", en: "finally", bn: "অবশেষে" },
  { id: 476, lesson: 8, kanji: "お巡りさん", furigana: "おまわりさん", romaji: "omawarisan", en: "policeman", bn: "টহল পুলিশ" },
  { id: 477, lesson: 8, kanji: "クッキー", furigana: "クッキー", romaji: "kukkii", en: "cookie", bn: "কুকি / বিস্কুট" },
  { id: 478, lesson: 8, kanji: "（お）団子", furigana: "（お）だんご", romaji: "(o)dango", en: "rice dumpling", bn: "ডাঙ্গো (চালের মিষ্টি ডাম্পলিং)" },
  { id: 479, lesson: 8, kanji: "湖", furigana: "みずうみ", romaji: "mizuumi", en: "lake", bn: "হ্রদ" },
  { id: 480, lesson: 8, kanji: "～さん（駅員さん）", furigana: "～さん（えきいんさん）", romaji: "~san (ekiinsan)", en: "Mr./Ms. (station employee)", bn: "মহাশয় (স্টেশন কর্মী মহাশয়)" },
  { id: 481, lesson: 8, kanji: "送る", furigana: "おくる", romaji: "okuru", en: "send off, take someone somewhere", bn: "পৌঁছে দেওয়া / এগিয়ে দেওয়া" },
  { id: 482, lesson: 8, kanji: "車でうちまで送る", furigana: "くるまでうちまでおくる", romaji: "kuruma de uchi made okuru", en: "take someone home by car", bn: "গাড়িতে করে বাসায় পৌঁছে দেওয়া" },
  { id: 483, lesson: 483, kanji: "連れて行く", furigana: "つれていく", romaji: "tsurete iku", en: "take someone along", bn: "সাথে করে নিয়ে যাওয়া" },
  { id: 484, lesson: 8, kanji: "捕る", furigana: "とる", romaji: "toru", en: "catch", bn: "ধরা" },
  { id: 485, lesson: 8, kanji: "直す", furigana: "なおす", romaji: "naosu", en: "fix, correct, repair", bn: "মেরামত করা / ঠিক করা" },
  { id: 486, lesson: 8, kanji: "拾う", furigana: "ひろう", romaji: "hirou", en: "pick up", bn: "কুড়িয়ে নেওয়া" },
  { id: 487, lesson: 8, kanji: "譲る", furigana: "ゆずる", romaji: "yuzuru", en: "pass on, transfer to", bn: "ছেড়ে দেওয়া / হস্তান্তর করা" },
  { id: 488, lesson: 8, kanji: "助ける", furigana: "たすける", romaji: "tasukeru", en: "help, save", bn: "সাহায্য করা / বাঁচানো" },
  { id: 489, lesson: 8, kanji: "届ける", furigana: "とどける", romaji: "todokeru", en: "send, deliver", bn: "পৌঁছে দেওয়া" },
  { id: 490, lesson: 8, kanji: "迎えに来る", furigana: "むかえにくる", romaji: "mukaeni kuru", en: "come get someone", bn: "কাউকে নিতে আসা" },
  { id: 491, lesson: 8, kanji: "そんなに", furigana: "そんなに", romaji: "sonna ni", en: "like that, so much", bn: "এতটা / এমনভাবে" },
  { id: 492, lesson: 8, kanji: "ふーん", furigana: "ふーん", romaji: "fuun", en: "well ...", bn: "আচ্ছা..." },
  { id: 493, lesson: 8, kanji: "鏡", furigana: "かがみ", romaji: "kagami", en: "mirror", bn: "আয়না" },
  { id: 494, lesson: 8, kanji: "花瓶", furigana: "かびん", romaji: "kabin", en: "flower vase", bn: "ফুলদানি" },
  { id: 495, lesson: 8, kanji: "教授", furigana: "きょうじゅ", romaji: "kyouju", en: "professor", bn: "অধ্যাপক" },
  { id: 496, lesson: 8, kanji: "近所", furigana: "きんじょ", romaji: "kinjo", en: "neighborhood", bn: "প্রতিবেশ / আশপাশ" },
  { id: 497, lesson: 8, kanji: "この間", furigana: "このあいだ", romaji: "kono aida", en: "the other day, during this time", bn: "সেদিন / কিছুদিন আগে" },
  { id: 498, lesson: 8, kanji: "資料", furigana: "しりょう", romaji: "shiryou", en: "documents, materials", bn: "নথিপত্র / তথ্যসামগ্রী" },
  { id: 499, lesson: 8, kanji: "（お）茶碗", furigana: "（お）ちゃわん", romaji: "(o)chawan", en: "china cup, china bowl", bn: "ভাতের বাটি / চায়ের পেয়ালা" },
  { id: 500, lesson: 8, kanji: "机", furigana: "つくえ", romaji: "tsukue", en: "desk", bn: "পড়ার টেবিল" },
  { id: 501, lesson: 8, kanji: "人形", furigana: "にんぎょう", romaji: "ningyou", en: "doll, figure", bn: "পুতুল" },
  { id: 502, lesson: 8, kanji: "部長", furigana: "ぶちょう", romaji: "buchou", en: "department manager", bn: "বিভাগীয় প্রধান" },
  { id: 503, lesson: 8, kanji: "本棚", furigana: "ほんだな", romaji: "hondana", en: "bookshelf", bn: "বইয়ের তাক" },
  { id: 504, lesson: 8, kanji: "（お）礼", furigana: "（お）れい", romaji: "(o)rei", en: "thanks, appreciation", bn: "ধন্যবাদ / কৃতজ্ঞতা" },
  { id: 505, lesson: 8, kanji: "～先（アルバイト先）", furigana: "～さき（アルバイトさき）", romaji: "~saki (arubaitosaki)", en: "place where ~ (e.g. part-time job)", bn: "কাজের স্থান (পার্ট-টাইম কর্মস্থল)" },
  { id: 506, lesson: 8, kanji: "いただく", furigana: "いただく", romaji: "itadaku", en: "receive gratefully (humble)", bn: "গ্রহণ করা (বিনম্র রূপ)" },
  { id: 507, lesson: 8, kanji: "くださる", furigana: "くださる", romaji: "kudasaru", en: "receive gratefully from someone (respectful)", bn: "প্রদান করা (সম্মানসূচক)" },
  { id: 508, lesson: 8, kanji: "気持ちいい", furigana: "きもちいい", romaji: "kimochiii", en: "comfortable, pleasant", bn: "আরামদায়ক" },
  { id: 509, lesson: 8, kanji: "素敵（な）", furigana: "すてき（な）", romaji: "suteki (na)", en: "splendid, wonderful", bn: "চমৎকার" },
  { id: 510, lesson: 8, kanji: "どういたしまして", furigana: "どういたしまして", romaji: "dou itashimashite", en: "You're welcome", bn: "আপনাকেও ধন্যবাদ" },
  { id: 511, lesson: 8, kanji: "チヂミ", furigana: "チヂミ", romaji: "chijimi", en: "chijimi (Korean pancake)", bn: "চিজিমী (কোরিয়ান প্যানকেক)" },
  { id: 512, lesson: 8, kanji: "におい", furigana: "におい", romaji: "nioi", en: "smell", bn: "গন্ধ" },
  { id: 513, lesson: 8, kanji: "飾る", furigana: "かざる", romaji: "kazaru", en: "decorate", bn: "সাজানো" },
  { id: 514, lesson: 8, kanji: "いろんな", furigana: "いろんな", romaji: "ironna", en: "various", bn: "নানা রকমের" },
  { id: 515, lesson: 8, kanji: "乾杯", furigana: "かんぱい", romaji: "kanpai", en: "\"Bottoms up!\", \"Cheers\"", bn: "চিয়ার্স!" },

  // LESSON 9: アルバイト先で (At the Part-time Job)
  { id: 516, lesson: 9, kanji: "大切さ", furigana: "たいせつさ", romaji: "taisetsusa", en: "importance", bn: "গুরুত্ব" },
  { id: 517, lesson: 9, kanji: "恥ずかしい", furigana: "はずかしい", romaji: "hazukashii", en: "embarrassing", bn: "লজ্জাজনক" },
  { id: 518, lesson: 9, kanji: "ですから", furigana: "ですから", romaji: "desukara", en: "therefore", bn: "তাই / সে কারণে" },
  { id: 519, lesson: 9, kanji: "一度", furigana: "いちど", romaji: "ichido", en: "once, one time", bn: "একবার" },
  { id: 520, lesson: 9, kanji: "裏", furigana: "うら", romaji: "ura", en: "rear, back", bn: "পেছন" },
  { id: 521, lesson: 9, kanji: "オーブン", furigana: "オーブン", romaji: "oobun", en: "oven", bn: "ওভেন" },
  { id: 522, lesson: 9, kanji: "温度", furigana: "おんど", romaji: "ondo", en: "temperature", bn: "তাপমাত্রা" },
  { id: 523, lesson: 9, kanji: "紙", furigana: "かみ", romaji: "kami", en: "paper", bn: "কাগজ" },
  { id: 524, lesson: 9, kanji: "髪の毛", furigana: "かみのけ", romaji: "kaminoke", en: "hair", bn: "চুল" },
  { id: 525, lesson: 9, kanji: "代わり", furigana: "かわり", romaji: "kawari", en: "in place of, instead", bn: "পরিবর্তে" },
  { id: 526, lesson: 9, kanji: "シフト", furigana: "シフト", romaji: "shifuto", en: "shift", bn: "কাজের শিফট" },
  { id: 527, lesson: 9, kanji: "シール", furigana: "シール", romaji: "shiiru", en: "sticker, seal", bn: "স্টিকার" },
  { id: 528, lesson: 9, kanji: "スタッフ", furigana: "スタッフ", romaji: "sutaffu", en: "staff", bn: "কর্মীদল" },
  { id: 529, lesson: 9, kanji: "スニーカー", furigana: "スニーカー", romaji: "suniikaa", en: "sneakers", bn: "স্নিকার্স জুতো" },
  { id: 530, lesson: 9, kanji: "隅", furigana: "すみ", romaji: "sumi", en: "corner", bn: "কোণা" },
  { id: 531, lesson: 9, kanji: "洗剤", furigana: "せんざい", romaji: "senzai", en: "detergent, cleanser", bn: "ডিটারজেন্ট" },
  { id: 532, lesson: 9, kanji: "タイムカード", furigana: "タイムカード", romaji: "taimukaado", en: "time card", bn: "টাইম কার্ড" },
  { id: 533, lesson: 9, kanji: "誰か", furigana: "だれか", romaji: "dareka", en: "someone", bn: "কেউ একজন" },
  { id: 534, lesson: 9, kanji: "調理場", furigana: "ちょうりば", romaji: "chouriba", en: "cooking place, kitchen", bn: "রান্নাঘর" },
  { id: 535, lesson: 9, kanji: "月", furigana: "つき", romaji: "tsuki", en: "month", bn: "মাস" },
  { id: 536, lesson: 9, kanji: "前の月", furigana: "まえのつき", romaji: "mae no tsuki", en: "the previous month", bn: "গত মাস" },
  { id: 537, lesson: 9, kanji: "都合", furigana: "つごう", romaji: "tsugou", en: "schedule, convenience", bn: "সময়-সুবিধা" },
  { id: 538, lesson: 9, kanji: "伝票", furigana: "でんぴょう", romaji: "denpyou", en: "order slip", bn: "অর্ডারের রসিদ" },
  { id: 539, lesson: 9, kanji: "道具", furigana: "どうぐ", romaji: "dougu", en: "tool", bn: "সরঞ্জাম" },
  { id: 540, lesson: 9, kanji: "表", furigana: "ひょう", romaji: "hyou", en: "table, chart", bn: "তালিকা / চার্ট" },
  { id: 541, lesson: 9, kanji: "ホール", furigana: "ホール", romaji: "hooru", en: "hall, dining area", bn: "ডাইনিং হল" },
  { id: 542, lesson: 9, kanji: "毎月", furigana: "まいつき", romaji: "maitsuki", en: "every month", bn: "প্রতি মাসে" },
  { id: 543, lesson: 9, kanji: "マニュアル", furigana: "マニュアル", romaji: "manyuaru", en: "manual", bn: "নির্দেশিকাপত্র" },
  { id: 544, lesson: 9, kanji: "床", furigana: "ゆか", romaji: "yuka", en: "floor", bn: "মেঝে" },
  { id: 545, lesson: 9, kanji: "汚れ", furigana: "よごれ", romaji: "yogore", en: "dirtiness, stain", bn: "ময়লা / দাগ" },
  { id: 546, lesson: 9, kanji: "予定", furigana: "よてい", romaji: "yotei", en: "schedule, plan", bn: "পরিকল্পনা" },
  { id: 547, lesson: 9, kanji: "ルール", furigana: "ルール", romaji: "ruuru", en: "rule", bn: "নিয়ম" },
  { id: 548, lesson: 9, kanji: "～様（お客様）", furigana: "～さま（おきゃくさま）", romaji: "~sama (okyakusama)", en: "sir, madam (respectful for customers)", bn: "মহাশয় (সম্মানিত অতিথি)" },
  { id: 549, lesson: 9, kanji: "上がる", furigana: "あがる", romaji: "agaru", en: "rise, go up", bn: "ওপরে ওঠা" },
  { id: 550, lesson: 9, kanji: "空く", furigana: "あく", romaji: "aku", en: "become empty, vacant", bn: "খালি হওয়া" },
  { id: 551, lesson: 9, kanji: "押す", furigana: "おす", romaji: "osu", en: "punch, press", bn: "চাপা / পাঞ্চ করা" },
  { id: 552, lesson: 9, kanji: "タイムカードを押す", furigana: "タイムカードをおす", romaji: "taimukaado o osu", en: "punch a time card", bn: "টাইম কার্ড পাঞ্চ করা" },
  { id: 553, lesson: 9, kanji: "乾く", furigana: "かわく", romaji: "kawaku", en: "dry", bn: "শুকানো" },
  { id: 554, lesson: 9, kanji: "代わる", furigana: "かわる", romaji: "kawaru", en: "replace, take over", bn: "বদলানো / অন্যের দায়িত্ব নেওয়া" },
  { id: 555, lesson: 9, kanji: "アルバイトを代わる", furigana: "アルバイトをかわる", romaji: "arubaito o kawaru", en: "replace someone's shift", bn: "অন্যের বদলে ডিউটি করা" },
  { id: 556, lesson: 9, kanji: "断る", furigana: "ことわる", romaji: "kotowaru", en: "turn down, deny", bn: "প্রত্যাখ্যান করা" },
  { id: 557, lesson: 9, kanji: "しまう", furigana: "しまう", romaji: "shimau", en: "put away", bn: "গুছিয়ে রাখা" },
  { id: 558, lesson: 9, kanji: "滑る", furigana: "すべる", romaji: "suberu", en: "slide, slip", bn: "পিছলে যাওয়া" },
  { id: 559, lesson: 9, kanji: "出す", furigana: "だす", romaji: "dasu", en: "take out, come out", bn: "বের করা" },
  { id: 560, lesson: 9, kanji: "ごみを出す", furigana: "ごみをだす", romaji: "gomi o dasu", en: "take out the garbage", bn: "ময়লা বাইরে ফেলা" },
  { id: 561, lesson: 9, kanji: "運ぶ", furigana: "はこぶ", romaji: "hakobu", en: "carry", bn: "বহন করা" },
  { id: 562, lesson: 9, kanji: "拭く", furigana: "ふく", romaji: "fuku", en: "wipe", bn: "মোছা" },
  { id: 563, lesson: 9, kanji: "干す", furigana: "ほす", romaji: "hosu", en: "hang out to dry", bn: "রোদে শুকাতে দেওয়া" },
  { id: 564, lesson: 9, kanji: "呼ぶ", furigana: "よぶ", romaji: "yobu", en: "call", bn: "ডাকা" },
  { id: 565, lesson: 9, kanji: "渡す", furigana: "わたす", romaji: "watasu", en: "hand over", bn: "হস্তান্তর করা" },
  { id: 566, lesson: 9, kanji: "上げる", furigana: "あげる", romaji: "ageru", en: "raise", bn: "তোলা" },
  { id: 567, lesson: 9, kanji: "下げる", furigana: "さげる", romaji: "sageru", en: "lower", bn: "নামানো" },
  { id: 568, lesson: 9, kanji: "片付ける", furigana: "かたづける", romaji: "katadukeru", en: "clean up, tidy", bn: "গুছিয়ে রাখা" },
  { id: 569, lesson: 9, kanji: "着替える", furigana: "きがえる", romaji: "kigaeru", en: "change clothes", bn: "পোশাক বদলানো" },
  { id: 570, lesson: 9, kanji: "足りる", furigana: "たりる", romaji: "tariru", en: "be enough", bn: "যথেষ্ট হওয়া" },
  { id: 571, lesson: 9, kanji: "つける", furigana: "つける", romaji: "tsukeru", en: "attach, put on", bn: "পরা / লাগানো" },
  { id: 572, lesson: 9, kanji: "アクセサリーをつける", furigana: "アクセサリーをつける", romaji: "akusesarii o tsukeru", en: "put on jewelry", bn: "অলংকার পরা" },
  { id: 573, lesson: 9, kanji: "並べる", furigana: "ならべる", romaji: "naraberu", en: "line up, arrange", bn: "সারি করে সাজানো" },
  { id: 574, lesson: 9, kanji: "燃える", furigana: "もえる", romaji: "moeru", en: "burn", bn: "পুড়ে যাওয়া" },
  { id: 575, lesson: 9, kanji: "あいさつ・する", furigana: "あいさつする", romaji: "aisatsu suru", en: "greet", bn: "অভিবাদন জানানো" },
  { id: 576, lesson: 9, kanji: "おしゃべり・する", furigana: "おしゃべりする", romaji: "oshaberi suru", en: "talk, chat", bn: "গল্পগুজব করা" },
  { id: 577, lesson: 9, kanji: "チェック・する", furigana: "チェックする", romaji: "chekku suru", en: "check", bn: "পরীক্ষা করা" },
  { id: 578, lesson: 9, kanji: "邪魔（な）", furigana: "じゃま（な）", romaji: "jama (na)", en: "distraction, hindrance", bn: "বাধার কারণ / অসুবিধা" },
  { id: 579, lesson: 9, kanji: "丁寧（な）", furigana: "ていねい（な）", romaji: "teinei (na)", en: "polite", bn: "ভদ্র / মার্জিত" },
  { id: 580, lesson: 9, kanji: "しっかり", furigana: "しっかり", romaji: "shikkari", en: "properly, adequately", bn: "ভালোভাবে / শক্তভাবে" },
  { id: 581, lesson: 9, kanji: "絶対に", furigana: "ぜったいに", romaji: "zettai ni", en: "absolutely", bn: "অবশ্যই / নিশ্চিতভাবে" },
  { id: 582, lesson: 9, kanji: "はっきり", furigana: "はっきり", romaji: "hakkiri", en: "clearly", bn: "স্পষ্টভাবে" },
  { id: 583, lesson: 9, kanji: "大きな", furigana: "おおきな", romaji: "ookina", en: "large", bn: "বড়" },
  { id: 584, lesson: 9, kanji: "お手洗い", furigana: "おてあらい", romaji: "otearai", en: "washroom, toilet", bn: "শৌচাগার" },
  { id: 585, lesson: 9, kanji: "ガス", furigana: "ガス", romaji: "gasu", en: "gas", bn: "গ্যাস" },
  { id: 586, lesson: 9, kanji: "ガソリン", furigana: "ガソリン", romaji: "gasorin", en: "gasoline", bn: "পেট্রোল" },
  { id: 587, lesson: 9, kanji: "そのまま", furigana: "そのまま", romaji: "sonomama", en: "as is, without change", bn: "যেভাবে আছে সেভাবেই" },
  { id: 588, lesson: 9, kanji: "バター", furigana: "バター", romaji: "bataa", en: "butter", bn: "মাখন" },
  { id: 589, lesson: 9, kanji: "引き出し", furigana: "ひきだし", romaji: "hikidashi", en: "drawer", bn: "ড্রয়ার" },
  { id: 590, lesson: 9, kanji: "ひも", furigana: "ひも", romaji: "himo", en: "string", bn: "দড়ি" },
  { id: 591, lesson: 9, kanji: "袋", furigana: "ふくろ", romaji: "fukuro", en: "bag, pouch", bn: "ব্যাগ / থলে" },
  { id: 592, lesson: 9, kanji: "瓶", furigana: "びん", romaji: "bin", en: "bottle, jar", bn: "কাঁচের বোতল" },
  { id: 593, lesson: 9, kanji: "モップ", furigana: "モップ", romaji: "moppu", en: "mop", bn: "মোছার মপ" },
  { id: 594, lesson: 9, kanji: "～袋（ごみ袋）", furigana: "～ぶくろ（ごみぶくろ）", romaji: "~bukuro (gomibukuro)", en: "~ bag (garbage bag)", bn: "ব্যাগ (ময়লার ব্যাগ)" },
  { id: 595, lesson: 9, kanji: "決まる", furigana: "きまる", romaji: "kimaru", en: "decide, be settled", bn: "নির্ধারিত হওয়া" },
  { id: 596, lesson: 9, kanji: "届く", furigana: "とどく", romaji: "todoku", en: "reach, arrive", bn: "পৌঁছানো" },
  { id: 597, lesson: 9, kanji: "かける", furigana: "かける", romaji: "kakeru", en: "rest on, sit", bn: "বসা" },
  { id: 598, lesson: 9, kanji: "こちらのいすにおかけください", furigana: "こちらのいすにおかけください", romaji: "kochira no isu ni okake kudasai", en: "\"Please have a seat here.\"", bn: "দয়া করে এই চেয়ারে বসুন" },
  { id: 599, lesson: 9, kanji: "切れる", furigana: "きれる", romaji: "kireru", en: "run out of", bn: "ফুরিয়ে যাওয়া" },
  { id: 600, lesson: 9, kanji: "焦げる", furigana: "こげる", romaji: "kogeru", en: "get burned", bn: "পুড়ে যাওয়া" },
  { id: 601, lesson: 9, kanji: "確かめる", furigana: "たしかめる", romaji: "tashikameru", en: "make sure, confirm", bn: "নিশ্চিত করা" },
  { id: 602, lesson: 9, kanji: "破れる", furigana: "やぶれる", romaji: "yabureru", en: "break, tear", bn: "ছিঁড়ে যাওয়া" },
  { id: 603, lesson: 9, kanji: "休憩・する", furigana: "きゅうけいする", romaji: "kyuukei suru", en: "take a break", bn: "বিরতি নেওয়া" },
  { id: 604, lesson: 9, kanji: "注意・する", furigana: "ちゅういする", romaji: "chuui suru", en: "pay attention", bn: "মনোযোগ দেওয়া / সতর্ক করা" },
  { id: 605, lesson: 9, kanji: "ご注意ください", furigana: "ごちゅういください", romaji: "gochuui kudasai", en: "\"Pay attention / Please be careful.\"", bn: "অনুগ্রহ করে সতর্ক থাকুন" },
  { id: 606, lesson: 9, kanji: "少々", furigana: "しょうしょう", romaji: "shoushou", en: "a little bit", bn: "সামান্য / কিছুক্ষণ" },
  { id: 607, lesson: 9, kanji: "お先にどうぞ", furigana: "おさきにどうぞ", romaji: "osaki ni douzo", en: "Please go ahead", bn: "আপনি আগে যান" },
  { id: 608, lesson: 9, kanji: "ご自由に", furigana: "ごじゆうに", romaji: "gojiyuu ni", en: "Please feel free", bn: "নিঃসংকোচে / ইচ্ছামতো" },
  { id: 609, lesson: 9, kanji: "申し訳ないんですが", furigana: "もうしわけないんですが", romaji: "moushiwake nai n desu ga", en: "I am sorry, but ...", bn: "অত্যন্ত দুঃখিত, কিন্তু..." },
  { id: 610, lesson: 9, kanji: "気をつける", furigana: "きをつける", romaji: "ki o tsukeru", en: "be careful", bn: "সাবধান হওয়া" },
  { id: 611, lesson: 9, kanji: "最初に", furigana: "さいしょに", romaji: "saisho ni", en: "first of all", bn: "সর্বপ্রথম" },
  { id: 612, lesson: 9, kanji: "先に", furigana: "さきに", romaji: "saki ni", en: "before, ahead, first", bn: "আগে / পূর্বে" }
];
