// Can-Do Competencies for all 15 lessons of できる日本語 初中級
window.CAN_DO_GOALS = [
  {
    lesson: 1,
    title: "新しい一歩",
    titleEn: "A New Step",
    goalJp: "初めて会った人に丁寧に自己紹介したり、印象よく問い合わせしたりすることができる。",
    goalEn: "Become able to politely introduce yourself to people you meet for the first time and make inquires that leave a good impression."
  },
  {
    lesson: 2,
    title: "楽しいショッピング",
    titleEn: "Fun Shopping",
    goalJp: "お店やレストランで友達と商品やメニューについて話したり、お店の人と話しながら買い物したりすることができる。",
    goalEn: "Become able to talk about products in stores and menus in restaurants with friends and shop while talking to shop assistants."
  },
  {
    lesson: 3,
    title: "私の目標",
    titleEn: "My Goals",
    goalJp: "自分の目標や計画を話したり進路の参考のために周りの人から話を聞いたりすることができる。",
    goalEn: "Become able to talk about your goals and plans and ask advice from people around you about what path to choose."
  },
  {
    lesson: 4,
    title: "住んでいる町で",
    titleEn: "In the Town Where I Live",
    goalJp: "日本の生活を楽しむために住んでいる町の情報を教え合って、その情報をもとに行動することができる。",
    goalEn: "Become able to share information on the town where you live and take action based on such information in order to enjoy your life in Japan."
  },
  {
    lesson: 5,
    title: "大変な1日",
    titleEn: "A Tough Day",
    goalJp: "突然のハプニングにあったとき、簡単なことなら事情を説明して、対処することができる。",
    goalEn: "Become able to explain situations, if simple ones, that you have suddenly encountered and respond to such situations."
  },
  {
    lesson: 6,
    title: "旅行に行こう",
    titleEn: "Let's Go on a Trip",
    goalJp: "旅行に行くために事前に情報を収集したり相談したりして、旅行に行く前の準備ができる。",
    goalEn: "Become able to make preparations before going on a trip such as collecting information and consulting with others."
  },
  {
    lesson: 7,
    title: "西川さんの家へ",
    titleEn: "To Mr. Nishikawa's House",
    goalJp: "日本人の家へ行ったとき、場面と関係性を考えながら、その家の人との交流を楽しむことができる。",
    goalEn: "Become able to enjoy interacting with Japanese people when visiting their house while considering the situation there and the relationship with them."
  },
  {
    lesson: 8,
    title: "ありがとう",
    titleEn: "Thank You",
    goalJp: "これまでの経験の中でしてもらってうれしかったことについて感謝の気持ちを表現することができる。",
    goalEn: "Become able to express your feeling of gratitude about something someone has done for you that made you happy."
  },
  {
    lesson: 9,
    title: "アルバイト先で",
    titleEn: "At the Part-Time Job",
    goalJp: "集団の中で気持ちよく仕事ができるように、周りの人のことを考えながら、会話することができる。",
    goalEn: "Become able to converse with co-workers in order to work happily within a group while considering the people around you."
  },
  {
    lesson: 10,
    title: "旅行に行って",
    titleEn: "Going on a Trip",
    goalJp: "旅行中に起こった困った状況や今の状況を他の人に伝えたり、観光スポットで目にした風景や建物について簡単に説明することができる。",
    goalEn: "Become able to communicate difficult situations you experienced during a trip to others and simply explain the scenery and buildings you saw at tourist spots."
  },
  {
    lesson: 11,
    title: "地域社会の中で",
    titleEn: "In the Local Community",
    goalJp: "地域の日本人に、自分の最近の生活や今困っていることなどについて話したり、地域の活動に参加したりすることができる。",
    goalEn: "Become able to talk about your life and the difficulties you have now in Japan with Japanese people in your local area and participate in local activities."
  },
  {
    lesson: 12,
    title: "私の健康法",
    titleEn: "My Health Method",
    goalJp: "健康を維持するための方法や体調がよくないときの対処法について、周囲の人と情報を交換することができる。",
    goalEn: "Become able to exchange information with people around you about how you maintain your health and what you do when you don't feel well."
  },
  {
    lesson: 13,
    title: "親の気持ち・子の気持ち",
    titleEn: "Parents' and Children's Feelings",
    goalJp: "テレビや街中で気になることを見かけたとき、それについて意見を言ったり、それに関する自分の経験を話したりすることができる。",
    goalEn: "Become able to express your opinion about something interesting you saw on television or on the street and talk about your related experiences."
  },
  {
    lesson: 14,
    title: "イベント・行事",
    titleEn: "Events & Customs",
    goalJp: "周りの日本人に自分の国・町についてより知ってもらうために、自分の国・町の行事や習慣について説明することができる。",
    goalEn: "Become able to explain events and customs from your country/region so that Japanese people around you can learn more about your country/region."
  },
  {
    lesson: 15,
    title: "気になるニュース",
    titleEn: "News of Interest",
    goalJp: "日々の生活の中で気になるニュースや事柄について、自分なりに疑問を持って調べ考えたことを周りの人に伝えて、やりとりすることができる。",
    goalEn: "Become able to communicate and converse with people around you about what you researched and considered with your own questions about the news and events which interest you in your everyday life."
  }
];

// Vocabulary List for Lessons 1 - 7
window.VOCABULARY_PART1 = [
  // LESSON 1: 新しい一歩 (A New Step)
  { id: 1, lesson: 1, kanji: "自己紹介", furigana: "じこしょうかい", romaji: "jikoshoukai", en: "self-introduction", bn: "আত্মপরিচয়" },
  { id: 2, lesson: 1, kanji: "方", furigana: "かた", romaji: "kata", en: "person (respectful language referring to someone else)", bn: "ব্যক্তি / মহাশয় (সম্মানসূচক)" },
  { id: 3, lesson: 1, kanji: "者", furigana: "もの", romaji: "mono", en: "person (humble language referring to oneself)", bn: "ব্যক্তি (বিনম্র)" },
  { id: 4, lesson: 1, kanji: "（お）刺身", furigana: "（お）さしみ", romaji: "(o)sashimi", en: "sashimi (thinly sliced raw seafood)", bn: "সাশিমি (কাঁচা মাছের সুস্বাদু পদ)" },
  { id: 5, lesson: 1, kanji: "チラシ", furigana: "チラシ", romaji: "chirashi", en: "leaflet, flyer", bn: "প্রচারপত্র / লিফলেট" },
  { id: 6, lesson: 1, kanji: "問い合わせ", furigana: "といあわせ", romaji: "toiawase", en: "inquiry", bn: "অনুসন্ধান / খোঁজখবর" },
  { id: 7, lesson: 1, kanji: "日常会話", furigana: "にちじょうかいわ", romaji: "nichijoukaiwa", en: "daily conversation", bn: "দৈনন্দিন কথোপকথন" },
  { id: 8, lesson: 1, kanji: "半年", furigana: "はんとし", romaji: "hantoshi", en: "half-year", bn: "ছয় মাস / অর্ধ বছর" },
  { id: 9, lesson: 1, kanji: "ホームページ", furigana: "ホームページ", romaji: "hoomupeeji", en: "website", bn: "ওয়েবসাইট" },
  { id: 10, lesson: 1, kanji: "面接", furigana: "めんせつ", romaji: "mensetsu", en: "interview", bn: "সাক্ষাৎকার / ইন্টারভিউ" },
  { id: 11, lesson: 1, kanji: "履歴書", furigana: "りれきしょ", romaji: "rirekisho", en: "resume, CV", bn: "জীবনবৃত্তান্ত / সিভি" },
  { id: 12, lesson: 1, kanji: "思い出す", furigana: "おもいだす", romaji: "omoidasu", en: "remember, recall", bn: "মনে পড়া / স্মরণ করা" },
  { id: 13, lesson: 1, kanji: "希望する", furigana: "きぼうする", romaji: "kibou suru", en: "desire, wish", bn: "আশা করা / চাওয়া" },
  { id: 14, lesson: 1, kanji: "募集する", furigana: "ぼしゅうする", romaji: "boshuu suru", en: "recruit, put out a call for", bn: "নিয়োগ দেওয়া / লোক খোঁজা" },
  { id: 15, lesson: 1, kanji: "入力する", furigana: "にゅうりょくする", romaji: "nyuuryoku suru", en: "input (data)", bn: "তথ্য দেওয়া / ইনপুট করা" },
  { id: 16, lesson: 1, kanji: "それでは", furigana: "それでは", romaji: "soredewa", en: "well, then (at sentence start)", bn: "তাহলে / বেশ" },
  { id: 17, lesson: 1, kanji: "では", furigana: "では", romaji: "dewa", en: "in that case, if so", bn: "তাহলে" },
  { id: 18, lesson: 1, kanji: "いらっしゃいます", furigana: "いらっしゃいます", romaji: "irasshaimasu", en: "go, come (respectful)", bn: "আসেন / যান (সম্মানসূচক)" },
  { id: 19, lesson: 1, kanji: "参りました", furigana: "まいりました", romaji: "mairimashita", en: "come, go (humble past)", bn: "এসেছি / এসেছি (বিনম্র রূপ)" },
  { id: 20, lesson: 1, kanji: "～と申します", furigana: "～ともうします", romaji: "~ to moushimasu", en: "\"My name is ~\" (humble)", bn: "আমার নাম ~ (বিনম্র)" },
  { id: 21, lesson: 1, kanji: "お先に失礼します", furigana: "おさきにしつれいします", romaji: "osaki ni shitsurei shimasu", en: "\"Excuse me for leaving first\"", bn: "আমি আগে বিদায় নিচ্ছি" },
  { id: 22, lesson: 1, kanji: "こちらへどうぞ", furigana: "こちらへどうぞ", romaji: "kochira e douzo", en: "\"Please come this way\"", bn: "দয়া করে এদিকে আসুন" },
  { id: 23, lesson: 1, kanji: "失礼します", furigana: "しつれいします", romaji: "shitsurei shimasu", en: "\"Excuse me\"", bn: "মাফ করবেন / বিদায় নিচ্ছি" },
  { id: 24, lesson: 1, kanji: "少々お待ちください", furigana: "しょうしょうおまちください", romaji: "shoushou omachi kudasai", en: "\"Please wait a moment\"", bn: "দয়া করে একটু অপেক্ষা করুন" },
  { id: 25, lesson: 1, kanji: "よろしくお願いいたします", furigana: "よろしくおねがいいたします", romaji: "yoroshiku onegai itashimasu", en: "\"I look forward to working with you\"", bn: "আপনার সহযোগিতা কামনা করছি" },
  { id: 26, lesson: 1, kanji: "意見", furigana: "いけん", romaji: "iken", en: "opinion", bn: "মতামত" },
  { id: 27, lesson: 1, kanji: "お年寄り", furigana: "おとしより", romaji: "otoshiyori", en: "elderly person", bn: "বয়োজ্যেষ্ঠ ব্যক্তি" },
  { id: 28, lesson: 1, kanji: "楽器", furigana: "がっき", romaji: "gakki", en: "musical instrument", bn: "বাদ্যযন্ত্র" },
  { id: 29, lesson: 1, kanji: "言葉", furigana: "ことば", romaji: "kotoba", en: "words, language", bn: "শব্দ / ভাষা" },
  { id: 30, lesson: 1, kanji: "自分", furigana: "じぶん", romaji: "jibun", en: "oneself", bn: "নিজে" },
  { id: 31, lesson: 1, kanji: "出身", furigana: "しゅっしん", romaji: "shusshin", en: "hometown, home country", bn: "জন্মস্থান / নিজ শহর" },
  { id: 32, lesson: 1, kanji: "建物", furigana: "たてもの", romaji: "tatemono", en: "building", bn: "ভবন / দালান" },
  { id: 33, lesson: 1, kanji: "話", furigana: "はなし", romaji: "hanashi", en: "conversation, talk", bn: "কথা / গল্প" },
  { id: 34, lesson: 1, kanji: "野外ライブ", furigana: "やがいらいぶ", romaji: "yagai raibu", en: "live outdoor concert", bn: "উন্মুক্ত মঞ্চের কনসার্ট" },
  { id: 35, lesson: 1, kanji: "歴史", furigana: "れきし", romaji: "rekishi", en: "history", bn: "ইতিহাস" },
  { id: 36, lesson: 1, kanji: "～個", furigana: "～こ", romaji: "~ko", en: "things (counter word)", bn: "টি / খানা (বস্তু গণনা)" },
  { id: 37, lesson: 1, kanji: "～地（観光地）", furigana: "～ち（かんこうち）", romaji: "~chi (kankouchi)", en: "place, spot (sightseeing spot)", bn: "স্থান (যেমন: দর্শনীয় স্থান)" },
  { id: 38, lesson: 1, kanji: "聞き取る", furigana: "ききとる", romaji: "kikitoru", en: "hear and understand", bn: "শুনে বুঝতে পারা" },
  { id: 39, lesson: 1, kanji: "覚える", furigana: "おぼえる", romaji: "oboeru", en: "remember, memorize", bn: "মনে রাখা / মুখস্থ করা" },
  { id: 40, lesson: 1, kanji: "応援する", furigana: "おうえんする", romaji: "ouen suru", en: "encourage, cheer on", bn: "উৎসাহ দেওয়া / সমর্থন করা" },
  { id: 41, lesson: 1, kanji: "サイクリングする", furigana: "さいくりんぐする", romaji: "saikuringu suru", en: "do cycling", bn: "সাইকেল চালানো" },
  { id: 42, lesson: 1, kanji: "遅い", furigana: "おそい", romaji: "osoi", en: "slow, late", bn: "ধীরগতি / দেরিতে" },
  { id: 43, lesson: 1, kanji: "速い", furigana: "はやい", romaji: "hayai", en: "fast, quick", bn: "দ্রুত" },
  { id: 44, lesson: 1, kanji: "つまらない", furigana: "つまらない", romaji: "tsumaranai", en: "boring", bn: "বিরক্তিকর / একঘেয়ে" },
  { id: 45, lesson: 1, kanji: "得意（な）", furigana: "とくい（な）", romaji: "tokui (na)", en: "good at (something)", bn: "দক্ষ / পারদর্শী" },
  { id: 46, lesson: 1, kanji: "苦手（な）", furigana: "にがて（な）", romaji: "nigate (na)", en: "bad at (something)", bn: "দুর্বল / অপটু" },
  { id: 47, lesson: 1, kanji: "無理（な）", furigana: "むり（な）", romaji: "muri (na)", en: "impossible, unable to do", bn: "অসম্ভব / সাধ্যের বাইরে" },
  { id: 48, lesson: 1, kanji: "朝早く", furigana: "あさはやく", romaji: "asa hayaku", en: "early morning", bn: "সকাল সকাল / খুব ভোরে" },
  { id: 49, lesson: 1, kanji: "字幕", furigana: "じまく", romaji: "jimaku", en: "subtitles", bn: "সাবটাইটেল" },
  { id: 50, lesson: 1, kanji: "大好き（な）", furigana: "だいすき（な）", romaji: "daisuki (na)", en: "favorite, love", bn: "খুব পছন্দের" },
  { id: 51, lesson: 1, kanji: "だいたい", furigana: "だいたい", romaji: "daitai", en: "mostly, roughly", bn: "সাধারণত / অধিকাংশ সময়ে" },
  { id: 52, lesson: 1, kanji: "まず", furigana: "まず", romaji: "mazu", en: "at first, first of all", bn: "প্রথমে" },

  // LESSON 2: 楽しいショッピング (Fun Shopping)
  { id: 53, lesson: 2, kanji: "うれしい", furigana: "うれしい", romaji: "ureshii", en: "happy, glad", bn: "আনন্দিত / খুশি" },
  { id: 54, lesson: 2, kanji: "恥ずかしい", furigana: "はずかしい", romaji: "hazukashii", en: "embarrassing, shy", bn: "লজ্জাজনক / লাজুক" },
  { id: 55, lesson: 2, kanji: "次", furigana: "つぎ", romaji: "tsugi", en: "next", bn: "পরবর্তী" },
  { id: 56, lesson: 2, kanji: "もう一度", furigana: "もういちど", romaji: "mou ichido", en: "one more time, again", bn: "আরও একবার" },
  { id: 57, lesson: 2, kanji: "腕時計", furigana: "うでどけい", romaji: "udedokei", en: "wristwatch", bn: "হাতঘড়ি" },
  { id: 58, lesson: 2, kanji: "指輪", furigana: "ゆびわ", romaji: "yubiwa", en: "ring", bn: "আংটি" },
  { id: 59, lesson: 2, kanji: "コート", furigana: "コート", romaji: "kooto", en: "coat", bn: "কোট" },
  { id: 60, lesson: 2, kanji: "コートを着る", furigana: "コートをきる", romaji: "kooto o kiru", en: "put on a coat", bn: "কোট পরিধান করা" },
  { id: 61, lesson: 2, kanji: "ジーンズ", furigana: "ジーンズ", romaji: "jiinzu", en: "jeans", bn: "জিন্স প্যান্ট" },
  { id: 62, lesson: 2, kanji: "セーター", furigana: "セーター", romaji: "seetaa", en: "sweater", bn: "সোয়েটার" },
  { id: 63, lesson: 2, kanji: "画面", furigana: "がめん", romaji: "gamen", en: "screen, display", bn: "পর্দা / স্ক্রিন" },
  { id: 64, lesson: 2, kanji: "サイズ", furigana: "サイズ", romaji: "saizu", en: "size", bn: "মাপ / সাইজ" },
  { id: 65, lesson: 2, kanji: "数字", furigana: "すうじ", romaji: "suuji", en: "number, figure", bn: "সংখ্যা" },
  { id: 66, lesson: 2, kanji: "スーツケース", furigana: "スーツケース", romaji: "suutsukeesu", en: "suitcase", bn: "স্যুটকেস" },
  { id: 67, lesson: 2, kanji: "棚", furigana: "たな", romaji: "tana", en: "shelf", bn: "তাক" },
  { id: 68, lesson: 2, kanji: "取っ手", furigana: "とって", romaji: "totte", en: "handle, knob", bn: "হাতল" },
  { id: 69, lesson: 2, kanji: "ヒール", furigana: "ヒール", romaji: "hiiru", en: "(high) heels", bn: "হাই হিল জুতো" },
  { id: 70, lesson: 2, kanji: "ファスナー", furigana: "ファスナー", romaji: "fasunaa", en: "fastener, zipper", bn: "চেইন / জিপার" },
  { id: 71, lesson: 2, kanji: "ボタン", furigana: "ボタン", romaji: "botan", en: "button", bn: "বোতাম" },
  { id: 72, lesson: 2, kanji: "動く", furigana: "うごく", romaji: "ugoku", en: "move, function", bn: "নড়াচড়া করা / চলা" },
  { id: 73, lesson: 2, kanji: "違う", furigana: "ちがう", romaji: "chigau", en: "differ from, be different", bn: "ভিন্ন হওয়া / আলাদা" },
  { id: 74, lesson: 2, kanji: "イメージする", furigana: "イメージする", romaji: "imeeji suru", en: "imagine, visualize", bn: "কল্পনা করা" },
  { id: 75, lesson: 2, kanji: "説明する", furigana: "せつめいする", romaji: "setsumei suru", en: "explain", bn: "ব্যাখ্যা করা" },
  { id: 76, lesson: 2, kanji: "配達する", furigana: "はいたつする", romaji: "haitatsu suru", en: "deliver", bn: "পৌঁছে দেওয়া / ডেলিভারি" },
  { id: 77, lesson: 2, kanji: "重い", furigana: "おもい", romaji: "omoi", en: "heavy (weight)", bn: "ভারী" },
  { id: 78, lesson: 2, kanji: "軽い", furigana: "かるい", romaji: "karui", en: "light (weight)", bn: "হালকা" },
  { id: 79, lesson: 2, kanji: "ちょうどいい", furigana: "ちょうどいい", romaji: "choudo ii", en: "perfect, just right", bn: "একদম মানানসই / ঠিকঠাক" },
  { id: 80, lesson: 2, kanji: "丈夫（な）", furigana: "じょうぶ（な）", romaji: "joubu (na)", en: "sturdy, durable", bn: "মজবুত / টেকসই" },
  { id: 81, lesson: 2, kanji: "もっと", furigana: "もっと", romaji: "motto", en: "more", bn: "আরও" },
  { id: 82, lesson: 2, kanji: "もっと大きいかばんがほしい", furigana: "もっとおおきいかばんがほしい", romaji: "motto ookii kaban ga hoshii", en: "\"I want a larger bag\"", bn: "আরও বড় ব্যাগ চাই" },
  { id: 83, lesson: 2, kanji: "ちょっと", furigana: "ちょっと", romaji: "chotto", en: "a little bit", bn: "একটু / সামান্য" },
  { id: 84, lesson: 2, kanji: "いかがですか", furigana: "いかがですか", romaji: "ikaga desu ka", en: "\"How is it?\"", bn: "কেমন লাগছে?" },
  { id: 85, lesson: 2, kanji: "かしこまりました", furigana: "かしこまりました", romaji: "kashikomarimashita", en: "\"I understand / Certainly\" (humble)", bn: "বুঝতে পেরেছি / অবশ্যই" },
  { id: 86, lesson: 2, kanji: "意味", furigana: "いみ", romaji: "imi", en: "meaning", bn: "অর্থ / মানে" },
  { id: 87, lesson: 2, kanji: "営業中", furigana: "えいぎょうちゅう", romaji: "eigyouchuu", en: "open for business", bn: "খোলা (দোকান/রেস্তোরাঁ)" },
  { id: 88, lesson: 2, kanji: "定休日", furigana: "ていきゅうび", romaji: "teikyuubi", en: "regular holiday", bn: "সাপ্তাহিক ছুটির দিন" },
  { id: 89, lesson: 2, kanji: "大盛り", furigana: "おおもり", romaji: "oomori", en: "extra-large portion", bn: "অতিরিক্ত খাবার / বড় বাটি" },
  { id: 90, lesson: 2, kanji: "おかわり", furigana: "おかわり", romaji: "okawari", en: "refill, second helping", bn: "পুনরায় পরিবেশন" },
  { id: 91, lesson: 2, kanji: "親子丼", furigana: "おやこどん", romaji: "oyakodon", en: "chicken and egg rice bowl", bn: "ওয়াাকোদোন (মুরগি ও ডিমের বাটি)" },
  { id: 92, lesson: 2, kanji: "牛丼", furigana: "ぎゅうどん", romaji: "gyuudon", en: "beef rice bowl", bn: "গিউদোন (গরুর মাংসের বাটি)" },
  { id: 93, lesson: 2, kanji: "サンドイッチ", furigana: "サンドイッチ", romaji: "sandoitchi", en: "sandwich", bn: "স্যান্ডউইচ" },
  { id: 94, lesson: 2, kanji: "ソース", furigana: "ソース", romaji: "soosu", en: "sauce", bn: "সস" },
  { id: 95, lesson: 2, kanji: "とんかつにソースをかける", furigana: "とんかつにソースをかける", romaji: "tonkatsu ni soosu o kakeru", en: "\"put sauce on pork cutlet\"", bn: "টনকাৎসুর উপর সস দেওয়া" },
  { id: 96, lesson: 2, kanji: "セット", furigana: "セット", romaji: "setto", en: "meal set", bn: "সেট খাবার" },
  { id: 97, lesson: 2, kanji: "ドリンクバー", furigana: "ドリンクバー", romaji: "dorinkubaa", en: "self-service drink bar", bn: "সেলফ-সার্ভিস পানীয় কর্নার" },
  { id: 98, lesson: 2, kanji: "壁", furigana: "かべ", romaji: "kabe", en: "wall", bn: "দেয়াল" },
  { id: 99, lesson: 2, kanji: "カレンダー", furigana: "カレンダー", romaji: "karendaa", en: "calendar", bn: "ক্যালেন্ডার" },
  { id: 100, lesson: 2, kanji: "期間限定", furigana: "きかんげんてい", romaji: "kikan gentei", en: "limited period", bn: "সীমিত সময়ের জন্য" },
  { id: 101, lesson: 2, kanji: "最新", furigana: "さいしん", romaji: "saishin", en: "latest, newest", bn: "সর্বাধুনিক / নতুন" },
  { id: 102, lesson: 2, kanji: "商品", furigana: "しょうひん", romaji: "shouhin", en: "product, goods", bn: "পণ্যসামগ্রী" },
  { id: 103, lesson: 2, kanji: "世界地図", furigana: "せかいちず", romaji: "sekai chizu", en: "world map", bn: "বিশ্ব মানচিত্র" },
  { id: 104, lesson: 2, kanji: "送料", furigana: "そうりょう", romaji: "souryou", en: "shipping charges", bn: "ডেলিভারি বা পরিবহন চার্জ" },
  { id: 105, lesson: 2, kanji: "タイムサービス", furigana: "タイムサービス", romaji: "taimu saabisu", en: "limited time offer", bn: "নির্দিষ্ট সময়ের বিশেষ অফার" },
  { id: 106, lesson: 2, kanji: "半額", furigana: "はんがく", romaji: "hangaku", en: "half-price", bn: "অর্ধেক দাম" },
  { id: 107, lesson: 2, kanji: "フロアガイド", furigana: "フロアガイド", romaji: "furoa gaido", en: "floor guide", bn: "ফ্লোর গাইড" },
  { id: 108, lesson: 2, kanji: "本日", furigana: "ほんじつ", romaji: "honjitsu", en: "today", bn: "আজ / অদ্য" },
  { id: 109, lesson: 2, kanji: "量", furigana: "りょう", romaji: "ryou", en: "amount, quantity", bn: "পরিমাণ" },
  { id: 110, lesson: 2, kanji: "～券（割引券）", furigana: "～けん（わりびきけん）", romaji: "~ken (waribikiken)", en: "ticket (discount ticket, coupon)", bn: "টিকিট / কুপন (যেমন: ছাড়ের টিকিট)" },
  { id: 111, lesson: 2, kanji: "～放題（飲み放題）", furigana: "～ほうだい（のみほうだい）", romaji: "~houdai (nomihoudai)", en: "all-you-can ~ (all-you-can-drink)", bn: "সীমাহীন / ইচ্ছামতো (পানীয়)" },
  { id: 112, lesson: 2, kanji: "貼る", furigana: "はる", romaji: "haru", en: "affix, stick", bn: "লাগানো / সাঁটা" },
  { id: 113, lesson: 2, kanji: "かける", furigana: "かける", romaji: "kakeru", en: "hang, put on", bn: "ঝুলানো / লাগানো" },
  { id: 114, lesson: 2, kanji: "カレンダーをかける", furigana: "カレンダーをかける", romaji: "karendaa o kakeru", en: "hang up a calendar", bn: "ক্যালেন্ডার ঝুলানো" },
  { id: 115, lesson: 2, kanji: "ソースをかける", furigana: "ソースをかける", romaji: "soosu o kakeru", en: "put sauce on", bn: "সস দেওয়া" },
  { id: 116, lesson: 2, kanji: "両替する", furigana: "りょうがえする", romaji: "ryougae suru", en: "exchange money (small notes/coins)", bn: "খুচরা টাকা ভাঙানো" },
  { id: 117, lesson: 2, kanji: "割引する", furigana: "わりびきする", romaji: "waribiki suru", en: "discount", bn: "মূল্যছাড় দেওয়া" },
  { id: 118, lesson: 2, kanji: "得（な）", furigana: "とく（な）", romaji: "toku (na)", en: "advantageous, profitable", bn: "লাভজনক / সাশ্রয়ী" },
  { id: 119, lesson: 2, kanji: "どういう", furigana: "どういう", romaji: "dou iu", en: "what kind of", bn: "কেমন ধরনের" },
  { id: 120, lesson: 2, kanji: "もう～（もう一杯）", furigana: "もう～（もういっぱい）", romaji: "mou~ (mou ippai)", en: "another ~, more ~ (one more cup)", bn: "আরও এক (যেমন: আরও এক কাপ)" },
  { id: 121, lesson: 2, kanji: "折りたたみ傘", furigana: "おりたたみがさ", romaji: "oritatamigasa", en: "folding umbrella", bn: "ভাঁজ করা ছাতা" },
  { id: 122, lesson: 2, kanji: "リュックサック", furigana: "リュックサック", romaji: "ryukkusakku", en: "backpack, rucksack", bn: "ব্যাকপ্যাক" },
  { id: 123, lesson: 2, kanji: "デザート", furigana: "デザート", romaji: "dezaato", en: "dessert", bn: "ডেজার্ট / মিষ্টি খাবার" },
  { id: 124, lesson: 2, kanji: "背負う", furigana: "せおう", romaji: "seou", en: "carry on one's back", bn: "পিঠে বহন করা" },
  { id: 125, lesson: 2, kanji: "大変", furigana: "たいへん", romaji: "taihen", en: "very, extremely", bn: "অত্যন্ত / ভীষণ" },

  // LESSON 3: 私の目標 (My Goals)
  { id: 126, lesson: 3, kanji: "笑顔", furigana: "えがお", romaji: "egao", en: "smile", bn: "হাসিমুখ" },
  { id: 127, lesson: 3, kanji: "悲しい", furigana: "かなしい", romaji: "kanashii", en: "sad", bn: "দুঃখজনক / বিষাদময়" },
  { id: 128, lesson: 3, kanji: "アクセサリー", furigana: "アクセサリー", romaji: "akusesarii", en: "jewelry, accessory", bn: "গহনা / অলংকার" },
  { id: 129, lesson: 3, kanji: "学部", furigana: "がくぶ", romaji: "gakubu", en: "academic department, faculty", bn: "অনুষদ / বিভাগ" },
  { id: 130, lesson: 3, kanji: "カナダ", furigana: "カナダ", romaji: "kanada", en: "Canada", bn: "কানাডা" },
  { id: 131, lesson: 3, kanji: "給料", furigana: "きゅうりょう", romaji: "kyuuryou", en: "salary, wage", bn: "বেতন" },
  { id: 132, lesson: 3, kanji: "計画", furigana: "けいかく", romaji: "keikaku", en: "plan, program, project", bn: "পরিকল্পনা" },
  { id: 133, lesson: 3, kanji: "経済", furigana: "けいざい", romaji: "keizai", en: "economics, economy", bn: "অর্থনীতি" },
  { id: 134, lesson: 3, kanji: "見学会", furigana: "けんがくかい", romaji: "kengakukai", en: "observation tour", bn: "শিক্ষাসফর / পরিদর্শন" },
  { id: 135, lesson: 3, kanji: "答え", furigana: "こたえ", romaji: "kotae", en: "answer, response", bn: "উত্তর" },
  { id: 136, lesson: 3, kanji: "サークル", furigana: "サークル", romaji: "saakuru", en: "club, group", bn: "ক্লাব / সার্কেল" },
  { id: 137, lesson: 3, kanji: "試験", furigana: "しけん", romaji: "shiken", en: "examination", bn: "পরীক্ষা" },
  { id: 138, lesson: 3, kanji: "将来", furigana: "しょうらい", romaji: "shourai", en: "future", bn: "ভবিষ্যৎ" },
  { id: 139, lesson: 3, kanji: "説明会", furigana: "せつめいかい", romaji: "setsumeikai", en: "explanatory meeting", bn: "তথ্যমূলক সভা / ব্রিফিং" },
  { id: 140, lesson: 3, kanji: "専門学校", furigana: "せんもんがっこう", romaji: "senmon gakkou", en: "vocational school", bn: "কারিগরি বিদ্যালয়" },
  { id: 141, lesson: 3, kanji: "聴解", furigana: "ちょうかい", romaji: "choukai", en: "listening comprehension", bn: "শুনে বোঝার ক্ষমতা" },
  { id: 142, lesson: 3, kanji: "日本語能力試験", furigana: "にほんごのうりょくしけん", romaji: "nihongo nouryoku shiken", en: "Japanese Language Proficiency Test (JLPT)", bn: "জাপানি ভাষা দক্ষতা পরীক্ষা" },
  { id: 143, lesson: 3, kanji: "ビジネス", furigana: "ビジネス", romaji: "bijinesu", en: "business", bn: "ব্যবসা-বাণিজ্য" },
  { id: 144, lesson: 3, kanji: "法律", furigana: "ほうりつ", romaji: "houritsu", en: "law", bn: "আইন" },
  { id: 145, lesson: 3, kanji: "間違い", furigana: "まちがい", romaji: "machigai", en: "mistake, error", bn: "ভুল" },
  { id: 146, lesson: 3, kanji: "目標", furigana: "もくひょう", romaji: "mokuhyou", en: "goal, target", bn: "লক্ষ্য" },
  { id: 147, lesson: 3, kanji: "寮", furigana: "りょう", romaji: "ryou", en: "dormitory", bn: "ছাত্রাবাস / হোস্টেল" },
  { id: 148, lesson: 3, kanji: "～会社（旅行会社）", furigana: "～がいしゃ（りょこうがいしゃ）", romaji: "~kaisha (ryokougaisha)", en: "company (travel company)", bn: "কোম্পানি (যেমন: ট্রাভেল এজেন্সি)" },
  { id: 149, lesson: 3, kanji: "～料（授業料）", furigana: "～りょう（じゅぎょうりょう）", romaji: "~ryou (jugyouryou)", en: "fees, charges (tuition)", bn: "ফি / মাশুল (যেমন: টিউশন ফি)" },
  { id: 150, lesson: 3, kanji: "選ぶ", furigana: "えらぶ", romaji: "erabu", en: "select, choose", bn: "বাছাই করা / নির্বাচন করা" },
  { id: 151, lesson: 3, kanji: "悩む", furigana: "なやむ", romaji: "nayamu", en: "be troubled over, worried", bn: "দুশ্চিন্তায় ভোগা" },
  { id: 152, lesson: 3, kanji: "開く", furigana: "ひらく", romaji: "hiraku", en: "open", bn: "খোলা" },
  { id: 153, lesson: 3, kanji: "自分の店を開く", furigana: "じぶんのみせをひらく", romaji: "jibun no mise o hiraku", en: "open your own store", bn: "নিজের দোকান খোলা" },
  { id: 154, lesson: 3, kanji: "迷う", furigana: "まよう", romaji: "mayou", en: "waver, hesitate", bn: "দ্বিধাদ্বন্দ্বে পড়া" },
  { id: 155, lesson: 3, kanji: "国へ帰るかどうか迷っている", furigana: "くにへかえるかどうかまよっている", romaji: "kuni e kaeru ka dou ka mayotte iru", en: "wavering whether to return to my country", bn: "দেশে ফিরব কি না তা নিয়ে দ্বিধায় আছি" },
  { id: 156, lesson: 3, kanji: "受ける", furigana: "うける", romaji: "ukeru", en: "receive, take", bn: "নেওয়া / পরীক্ষা দেওয়া" },
  { id: 157, lesson: 3, kanji: "入学試験を受ける", furigana: "にゅうがくしけんをうける", romaji: "nyuugaku shiken o ukeru", en: "take an entrance examination", bn: "ভর্তি পরীক্ষা দেওয়া" },
  { id: 158, lesson: 3, kanji: "考える", furigana: "かんがえる", romaji: "kangaeru", en: "think about", bn: "চিন্তা করা" },
  { id: 159, lesson: 3, kanji: "決める", furigana: "きめる", romaji: "kimeru", en: "decide", bn: "সিদ্ধান্ত নেওয়া" },
  { id: 160, lesson: 3, kanji: "調べる", furigana: "しらべる", romaji: "shiraberu", en: "examine, investigate", bn: "অনুসন্ধান করা / খুঁজে দেখা" },
  { id: 161, lesson: 3, kanji: "続ける", furigana: "つづける", romaji: "tsuzukeru", en: "continue", bn: "চালিয়ে যাওয়া" },
  { id: 162, lesson: 3, kanji: "辞める", furigana: "やめる", romaji: "yameru", en: "stop, quit", bn: "ছেড়ে দেওয়া / পদত্যাগ করা" },
  { id: 163, lesson: 3, kanji: "案内する", furigana: "あんないする", romaji: "annai suru", en: "guide", bn: "পথ দেখানো / গাইড করা" },
  { id: 164, lesson: 3, kanji: "確認する", furigana: "かくにんする", romaji: "kakunin suru", en: "check, confirm", bn: "নিশ্চিত করা" },
  { id: 165, lesson: 3, kanji: "見学する", furigana: "けんがくする", romaji: "kengaku suru", en: "tour, observe", bn: "পরিদর্শন করা" },
  { id: 166, lesson: 3, kanji: "合格する", furigana: "ごうかくする", romaji: "goukaku suru", en: "pass (an examination)", bn: "পাস করা / উত্তীর্ণ হওয়া" },
  { id: 167, lesson: 3, kanji: "進学する", furigana: "しんがくする", romaji: "shingaku suru", en: "proceed to higher education", bn: "উচ্চশিক্ষায় ভর্তি হওয়া" },
  { id: 168, lesson: 3, kanji: "就職する", furigana: "しゅうしょくする", romaji: "shuushoku suru", en: "find a job, get employed", bn: "চাকরি পাওয়া" },
  { id: 169, lesson: 3, kanji: "専攻する", furigana: "せんこうする", romaji: "senkou suru", en: "specialize in, major in", bn: "প্রধান বিষয় নিয়ে পড়া" },
  { id: 170, lesson: 3, kanji: "相談する", furigana: "そうだんする", romaji: "soudan suru", en: "consult with, ask advice", bn: "পরামর্শ করা" },
  { id: 171, lesson: 3, kanji: "貯金する", furigana: "ちょきんする", romaji: "chokin suru", en: "save up money", bn: "টাকা জমানো" },
  { id: 172, lesson: 3, kanji: "通学する", furigana: "つうがくする", romaji: "tsuugaku suru", en: "commute to school", bn: "স্কুলে যাতায়াত করা" },
  { id: 173, lesson: 3, kanji: "翻訳する", furigana: "ほんやくする", romaji: "honyaku suru", en: "translate (written)", bn: "অনুবাদ করা" },
  { id: 174, lesson: 3, kanji: "正しい", furigana: "ただしい", romaji: "tadashii", en: "correct", bn: "সঠিক" },
  { id: 175, lesson: 3, kanji: "一生懸命", furigana: "いっしょうけんめい", romaji: "isshoukenmei", en: "do one's very best", bn: "আপ্রাণ চেষ্টা করা" },
  { id: 176, lesson: 3, kanji: "願書", furigana: "がんしょ", romaji: "gansho", en: "application form", bn: "আবেদনপত্র" },
  { id: 177, lesson: 3, kanji: "建築家", furigana: "けんちくか", romaji: "kenchikuka", en: "architect", bn: "স্থপতি" },
  { id: 178, lesson: 3, kanji: "事務室", furigana: "じむしつ", romaji: "jimushitsu", en: "office", bn: "কার্যালয় / অফিস কক্ষ" },
  { id: 179, lesson: 3, kanji: "書類", furigana: "しょるい", romaji: "shorui", en: "documents", bn: "কাগজপত্র / নথি" },
  { id: 180, lesson: 3, kanji: "スーツ", furigana: "スーツ", romaji: "suutsu", en: "business suit", bn: "স্যুট" },
  { id: 181, lesson: 3, kanji: "デザイナー", furigana: "デザイナー", romaji: "dezainaa", en: "designer", bn: "ডিজাইনার" },
  { id: 182, lesson: 3, kanji: "夢", furigana: "ゆめ", romaji: "yume", en: "dream, aspiration", bn: "স্বপ্ন / আকাঙ্ক্ষা" },
  { id: 183, lesson: 3, kanji: "将来の夢", furigana: "しょうらいのゆめ", romaji: "shourai no yume", en: "one's future dream", bn: "ভবিষ্যতের স্বপ্ন" },
  { id: 184, lesson: 3, kanji: "～中（今日中）", furigana: "～ちゅう（きょうじゅう）", romaji: "~chuu (kyoujuu)", en: "during (example: during today)", bn: "চলাকালীন (যেমন: আজকের মধ্যে)" },
  { id: 185, lesson: 3, kanji: "頑張る", furigana: "がんばる", romaji: "ganbaru", en: "do one's best", bn: "মনপ্রাণ দিয়ে চেষ্টা করা" },
  { id: 186, lesson: 3, kanji: "経営する", furigana: "けいえいする", romaji: "keiei suru", en: "manage (a business)", bn: "পরিচালনা করা" },
  { id: 187, lesson: 3, kanji: "受験する", furigana: "じゅけんする", romaji: "juken suru", en: "take an examination", bn: "পরীক্ষায় বসা" },
  { id: 188, lesson: 3, kanji: "スピーチする", furigana: "スピーチする", romaji: "supiichi suru", en: "give a speech", bn: "বক্তৃতা দেওয়া" },
  { id: 189, lesson: 3, kanji: "体験する", furigana: "たいけんする", romaji: "taiken suru", en: "experience firsthand", bn: "বাস্তব অভিজ্ঞতা নেওয়া" },
  { id: 190, lesson: 3, kanji: "デッサンする", furigana: "デッサンする", romaji: "dessan suru", en: "produce a drawing, sketch", bn: "স্কেচ আঁকা" },
  { id: 191, lesson: 3, kanji: "復習する", furigana: "ふくしゅうする", romaji: "fukushuu suru", en: "review (a lesson)", bn: "পুনরাবৃত্তি করা / রিভিশন দেওয়া" },
  { id: 192, lesson: 3, kanji: "予習する", furigana: "よしゅうする", romaji: "yoshuu suru", en: "prepare for (a lesson)", bn: "পূর্বপ্রস্তুতি নেওয়া" },
  { id: 193, lesson: 3, kanji: "パティシエ", furigana: "パティシエ", romaji: "patishie", en: "pastry baker", bn: "পেস্ট্রি শেফ" },
  { id: 194, lesson: 3, kanji: "通訳する", furigana: "つうやくする", romaji: "tsuuyaku suru", en: "interpret (translate orally)", bn: "মৌখিক অনুবাদ করা" },

  // LESSON 4: 住んでいる町で (In the Town Where I Live)
  { id: 195, lesson: 4, kanji: "味", furigana: "あじ", romaji: "aji", en: "taste, flavor", bn: "স্বাদ" },
  { id: 196, lesson: 4, kanji: "おばさん", furigana: "おばさん", romaji: "obasan", en: "ma'am, aunt", bn: "খালা / বয়স্কা মহিলা" },
  { id: 197, lesson: 4, kanji: "タコ", furigana: "タコ", romaji: "tako", en: "octopus", bn: "অক্টোপাস" },
  { id: 198, lesson: 4, kanji: "たこ焼き", furigana: "たこやき", romaji: "takoyaki", en: "takoyaki (fried octopus balls)", bn: "তাকোইয়াকি (ভাজা অক্টোপাস পিঠা)" },
  { id: 199, lesson: 4, kanji: "におい", furigana: "におい", romaji: "nioi", en: "smell", bn: "গন্ধ" },
  { id: 200, lesson: 4, kanji: "通る", furigana: "とおる", romaji: "tooru", en: "pass through", bn: "অতিক্রম করা / পার হওয়া" },
  { id: 201, lesson: 4, kanji: "似る", furigana: "にる", romaji: "niru", en: "be similar to", bn: "সদৃশ হওয়া / মিল থাকা" },
  { id: 202, lesson: 4, kanji: "丸い", furigana: "まるい", romaji: "marui", en: "round", bn: "গোল" },
  { id: 203, lesson: 4, kanji: "小さな", furigana: "ちいさな", romaji: "chiisana", en: "small", bn: "ছোট" },
  { id: 204, lesson: 4, kanji: "～がする", furigana: "～がする", romaji: "~ga suru", en: "make a (noise, smell)", bn: "অনুভূত হওয়া (শব্দ/গন্ধ)" },
  { id: 205, lesson: 4, kanji: "空港", furigana: "くうこう", romaji: "kuukou", en: "airport", bn: "বিমানবন্দর" },
  { id: 206, lesson: 4, kanji: "歯科", furigana: "しか", romaji: "shika", en: "dentist, dentistry", bn: "দন্তচিকিৎসা" },
  { id: 207, lesson: 4, kanji: "市役所", furigana: "しやくしょ", romaji: "shiyakusho", en: "city hall", bn: "নগর ভবন" },
  { id: 208, lesson: 4, kanji: "小学校", furigana: "しょうがっこう", romaji: "shougakkou", en: "elementary school", bn: "প্রাথমিক বিদ্যালয়" },
  { id: 209, lesson: 4, kanji: "美容院", furigana: "びよういん", romaji: "biyouin", en: "beauty salon", bn: "বিউটি পার্লার" },
  { id: 210, lesson: 4, kanji: "不動産", furigana: "ふどうさん", romaji: "fudousan", en: "real estate", bn: "রিয়েল এস্টেট" },
  { id: 211, lesson: 4, kanji: "交流会", furigana: "こうりゅうかい", romaji: "kouryuukai", en: "(cultural) exchange meeting", bn: "মতবিনিময় সভা" },
  { id: 212, lesson: 4, kanji: "茶道", furigana: "さどう", romaji: "sadou", en: "sado (Japanese tea ceremony)", bn: "জাপানি চা পরিবেশন রীতি" },
  { id: 213, lesson: 4, kanji: "三味線", furigana: "しゃみせん", romaji: "shamisen", en: "shamisen (three-stringed instrument)", bn: "শামিসেন (জাপানি বাদ্যযন্ত্র)" },
  { id: 214, lesson: 4, kanji: "市民", furigana: "しみん", romaji: "shimin", en: "citizen", bn: "নাগরিক" },
  { id: 215, lesson: 4, kanji: "種類", furigana: "しゅるい", romaji: "shurui", en: "type, kind", bn: "প্রকার / ধরন" },
  { id: 216, lesson: 4, kanji: "情報", furigana: "じょうほう", romaji: "jouhou", en: "information", bn: "তথ্য" },
  { id: 217, lesson: 4, kanji: "水道", furigana: "すいどう", romaji: "suidou", en: "waterworks, waterway", bn: "জল সরবরাহ ব্যবস্থা" },
  { id: 218, lesson: 4, kanji: "タオル", furigana: "タオル", romaji: "taoru", en: "towel", bn: "তোয়ালে" },
  { id: 219, lesson: 4, kanji: "てんぷら", furigana: "てんぷら", romaji: "tenpura", en: "tempura (deep-fried seafood/veg)", bn: "তেমপুরা (ভাজা জাপানি খাবার)" },
  { id: 220, lesson: 4, kanji: "方法", furigana: "ほうほう", romaji: "houhou", en: "method, technique, way", bn: "পদ্ধতি / উপায়" },
  { id: 221, lesson: 4, kanji: "理由", furigana: "りゆう", romaji: "riyuu", en: "reason", bn: "কারণ" },
  { id: 222, lesson: 4, kanji: "～場（サッカー場）", furigana: "～じょう（サッカーじょう）", romaji: "~jou (sakkaajou)", en: "place, location (soccer field)", bn: "মাঠ / স্থান (ফুটবল মাঠ)" },
  { id: 223, lesson: 4, kanji: "～センター（市民センター）", furigana: "～センター（しみんセンター）", romaji: "~sentaa (shiminsentaa)", en: "center (community center)", bn: "কেন্দ্র (নাগরিক কেন্দ্র)" },
  { id: 224, lesson: 4, kanji: "～口（西口）", furigana: "～ぐち（にしぐち）", romaji: "~guchi (nishiguchi)", en: "entrance, exit (west exit)", bn: "প্রবেশপথ / ফটক (পশ্চিম গেট)" },
  { id: 225, lesson: 4, kanji: "着く", furigana: "つく", romaji: "tsuku", en: "arrive", bn: "পৌঁছানো" },
  { id: 226, lesson: 4, kanji: "止まる", furigana: "とまる", romaji: "tomaru", en: "stop", bn: "থামা / বন্ধ হওয়া" },
  { id: 227, lesson: 4, kanji: "水が止まる", furigana: "みずがとまる", romaji: "mizu ga tomaru", en: "water has stopped running", bn: "পানি বন্ধ হওয়া" },
  { id: 228, lesson: 4, kanji: "知らせる", furigana: "しらせる", romaji: "shiraseru", en: "notify, inform", bn: "জানানো / খবর দেওয়া" },
  { id: 229, lesson: 4, kanji: "出る", furigana: "でる", romaji: "deru", en: "operate, depart", bn: "চলা / বের হওয়া" },
  { id: 230, lesson: 4, kanji: "バスが出る", furigana: "バスがでる", romaji: "basu ga deru", en: "run a bus service / departs", bn: "বাস ছাড়ে" },
  { id: 231, lesson: 4, kanji: "カットする", furigana: "カットする", romaji: "katto suru", en: "cut", bn: "চুল কাটা" },
  { id: 232, lesson: 4, kanji: "質問する", furigana: "しつもんする", romaji: "shitsumon suru", en: "ask a question", bn: "প্রশ্ন করা" },
  { id: 233, lesson: 4, kanji: "修理する", furigana: "しゅうりする", romaji: "shuuri suru", en: "repair", bn: "মেরামত করা" },
  { id: 234, lesson: 4, kanji: "利用する", furigana: "りようする", romaji: "riyou suru", en: "use, utilize", bn: "ব্যবহার করা" },
  { id: 235, lesson: 4, kanji: "必要（な）", furigana: "ひつよう（な）", romaji: "hitsuyou (na)", en: "needed, necessary", bn: "প্রয়োজনীয় / দরকারি" },
  { id: 236, lesson: 4, kanji: "区役所", furigana: "くやくしょ", romaji: "kuyakusho", en: "ward office", bn: "ওয়ার্ড অফিস" },
  { id: 237, lesson: 4, kanji: "大使館", furigana: "たいしかん", romaji: "taishikan", en: "embassy", bn: "দূতাবাস" },
  { id: 238, lesson: 4, kanji: "坂", furigana: "さか", romaji: "saka", en: "hill, slope", bn: "ঢাল / পাহাড়ের ঢাল" },
  { id: 239, lesson: 4, kanji: "次", furigana: "つぎ", romaji: "tsugi", en: "next", bn: "পরবর্তী" },
  { id: 240, lesson: 4, kanji: "～階建て", furigana: "～かいだて", romaji: "~kaidate", en: "building with ~ floors", bn: "তলা বিশিষ্ট ভবন" },
  { id: 241, lesson: 4, kanji: "～番線", furigana: "～ばんせん", romaji: "~bansen", en: "number ~ train line", bn: "নম্বর প্ল্যাটফর্ম / লাইন" },
  { id: 242, lesson: 4, kanji: "～メートル", furigana: "～メートル", romaji: "~meetoru", en: "meter", bn: "মিটার" },
  { id: 243, lesson: 4, kanji: "～行き（新宿行き）", furigana: "～ゆき（しんじゅくゆき）", romaji: "~yuki (shinjukuyuki)", en: "destination (train bound for Shinjuku)", bn: "গন্তব্য (শিনজুকু অভিমুখী)" },
  { id: 244, lesson: 4, kanji: "上る", furigana: "のぼる", romaji: "noboru", en: "move upward, climb", bn: "উপরে ওঠা" },
  { id: 245, lesson: 4, kanji: "下りる", furigana: "おりる", romaji: "oriru", en: "move downward, descend", bn: "নিচে নামা" },
  { id: 246, lesson: 4, kanji: "駐車する", furigana: "ちゅうしゃする", romaji: "chuusha suru", en: "park (a vehicle)", bn: "গাড়ি পার্ক করা" },
  { id: 247, lesson: 4, kanji: "中学校", furigana: "ちゅうがっこう", romaji: "chuugakkou", en: "junior high school", bn: "জুনিয়র হাই স্কুল" },
  { id: 248, lesson: 4, kanji: "方", furigana: "ほう", romaji: "hou", en: "towards, side, direction", bn: "দিক" },
  { id: 249, lesson: 4, kanji: "ラケット", furigana: "ラケット", romaji: "raketto", en: "racket", bn: "র‍্যাকেট" }
];
