// Complete Vocabulary for Lessons 10 to 15 from 『できる日本語 初中級 本冊』 and Master Export
window.VOCABULARY_PART3 = [
  // LESSON 10: 旅行に行って (Having Gone on a Trip)
  { id: 613, lesson: 10, kanji: "あめ", furigana: "あめ", romaji: "ame", en: "candy, sweets", bn: "ক্যান্ডি / মিষ্টি" },
  { id: 614, lesson: 10, kanji: "王様", furigana: "おうさま", romaji: "ousama", en: "king", bn: "রাজা" },
  { id: 615, lesson: 10, kanji: "クルミ", furigana: "クルミ", romaji: "kurumi", en: "walnut", bn: "আখরোট" },
  { id: 616, lesson: 10, kanji: "ゴマ", furigana: "ゴマ", romaji: "goma", en: "sesame", bn: "তিল" },
  { id: 617, lesson: 10, kanji: "誰でも", furigana: "だれでも", romaji: "dare demo", en: "anyone", bn: "যে কেউ" },
  { id: 618, lesson: 10, kanji: "伸ばす", furigana: "のばす", romaji: "nobasu", en: "stretch, extend", bn: "প্রসারিত করা / টানা" },
  { id: 619, lesson: 10, kanji: "巻く", furigana: "まく", romaji: "maku", en: "wind up, wrap around", bn: "জড়ানো / পেঁচানো" },
  { id: 620, lesson: 10, kanji: "丸い", furigana: "まるい", romaji: "marui", en: "round", bn: "গোল" },
  { id: 621, lesson: 10, kanji: "アイスクリーム", furigana: "アイスクリーム", romaji: "aisukuriimu", en: "ice cream", bn: "আইসক্রিম" },
  { id: 622, lesson: 10, kanji: "おじいさん", furigana: "おじいさん", romaji: "ojiisan", en: "an old man, grandfather", bn: "বৃদ্ধ লোক / দাদা-নানা" },
  { id: 623, lesson: 10, kanji: "近所のおじいさん", furigana: "きんじょのおじいさん", romaji: "kinjo no ojiisan", en: "an old man in the neighbourhood", bn: "পাড়ার বৃদ্ধ লোক" },
  { id: 624, lesson: 10, kanji: "おばあさん", furigana: "おばあさん", romaji: "obaasan", en: "an old woman, grandmother", bn: "বৃদ্ধা মহিলা / দাদি-নানি" },
  { id: 625, lesson: 10, kanji: "近所のおばあさん", furigana: "きんじょのおばあさん", romaji: "kinjo no obaasan", en: "an old woman in the neighbourhood", bn: "পাড়ার বৃদ্ধা মহিলা" },
  { id: 626, lesson: 10, kanji: "おにぎり", furigana: "おにぎり", romaji: "onigiri", en: "rice ball", bn: "ওনিগিরি (ভাতের বল)" },
  { id: 627, lesson: 10, kanji: "蚊", furigana: "か", romaji: "ka", en: "mosquito", bn: "মশা" },
  { id: 628, lesson: 10, kanji: "係", furigana: "かかり", romaji: "kakari", en: "person in charge", bn: "দায়িত্বপ্রাপ্ত কর্মী" },
  { id: 629, lesson: 10, kanji: "シカ", furigana: "シカ", romaji: "shika", en: "deer", bn: "হরিণ" },
  { id: 630, lesson: 10, kanji: "シングル", furigana: "シングル", romaji: "shinguru", en: "single (room/bed)", bn: "একক রুম / সিঙ্গেল" },
  { id: 631, lesson: 10, kanji: "ツイン", furigana: "ツイン", romaji: "tsuin", en: "twin (room)", bn: "টুইন রুম" },
  { id: 632, lesson: 10, kanji: "展望台", furigana: "てんぼうだい", romaji: "tenboudai", en: "viewing platform, observation deck", bn: "পর্যবেক্ষণ ডেক" },
  { id: 633, lesson: 10, kanji: "泥棒", furigana: "どろぼう", romaji: "dorobou", en: "thief, burglar", bn: "চোর" },
  { id: 634, lesson: 10, kanji: "バッテリー", furigana: "バッテリー", romaji: "batterii", en: "battery (rechargeable)", bn: "রিচার্জেবল ব্যাটারি" },
  { id: 635, lesson: 10, kanji: "フロント", furigana: "フロント", romaji: "furonto", en: "front desk", bn: "ফ্রন্ট ডেস্ক" },
  { id: 636, lesson: 10, kanji: "ポーチ", furigana: "ポーチ", romaji: "pouchi", en: "pouch", bn: "ছোট ব্যাগ / পাউচ" },
  { id: 637, lesson: 10, kanji: "ライブ", furigana: "ライブ", romaji: "raibu", en: "live concert, broadcast", bn: "লাইভ অনুষ্ঠান / কনসার্ট" },
  { id: 638, lesson: 10, kanji: "ロック", furigana: "ロック", romaji: "rokku", en: "rock (music)", bn: "রক মিউজিক" },
  { id: 639, lesson: 10, kanji: "かむ", furigana: "かむ", romaji: "kamu", en: "chew, bite", bn: "চিবানো / কামড়ানো" },
  { id: 640, lesson: 10, kanji: "配る", furigana: "くばる", romaji: "kubaru", en: "distribute", bn: "বণ্টন করা / বিলি করা" },
  { id: 641, lesson: 10, kanji: "刺す", furigana: "さす", romaji: "sasu", en: "bite, sting, stick with", bn: "কামড়ানো / হুল ফোটানো" },
  { id: 642, lesson: 10, kanji: "誘う", furigana: "さそう", romaji: "sasou", en: "invite, take out", bn: "আমন্ত্রণ জানানো / সাথে যেতে বলা" },
  { id: 643, lesson: 10, kanji: "頼む", furigana: "たのむ", romaji: "tanomu", en: "ask, request", bn: "অনুরোধ করা" },
  { id: 644, lesson: 10, kanji: "踏む", furigana: "ふむ", romaji: "fumu", en: "step on", bn: "পা মাড়ানো" },
  { id: 645, lesson: 10, kanji: "ぶつかる", furigana: "ぶつかる", romaji: "butsukaru", en: "hit, run against, collide", bn: "ধাক্কা লাগা" },
  { id: 646, lesson: 10, kanji: "けんか・する", furigana: "けんかする", romaji: "kenka suru", en: "argue, fight", bn: "ঝগড়া করা" },
  { id: 647, lesson: 10, kanji: "撮影・する", furigana: "さつえいする", romaji: "satsuei suru", en: "take a picture, record video", bn: "ছবি তোলা / ভিডিও করা" },
  { id: 648, lesson: 10, kanji: "充電・する", furigana: "じゅうでんする", romaji: "juuden suru", en: "charge (a battery)", bn: "চার্জ দেওয়া" },
  { id: 649, lesson: 10, kanji: "招待・する", furigana: "しょうたいする", romaji: "shoutai suru", en: "invite, ask", bn: "দাওয়াত দেওয়া" },
  { id: 650, lesson: 10, kanji: "タッチ・する", furigana: "タッチする", romaji: "tacchi suru", en: "touch, tap (screen)", bn: "স্পর্শ / ট্যাপ করা" },
  { id: 651, lesson: 10, kanji: "注意・する", furigana: "ちゅういする", romaji: "chuui suru", en: "advise, admonish, warn", bn: "সতর্ক করা" },
  { id: 652, lesson: 10, kanji: "係の人に注意される", furigana: "かかりのひとにちゅういされる", romaji: "kakari no hito ni chuui sareru", en: "be given notice by the staff", bn: "কর্মচারী কর্তৃক সতর্ক হওয়া" },
  { id: 653, lesson: 10, kanji: "通訳・する", furigana: "つうやくする", romaji: "tsuuyaku suru", en: "interpret (translate orally)", bn: "মৌখিক অনুবাদ করা" },
  { id: 654, lesson: 10, kanji: "発売・する", furigana: "はつばいする", romaji: "hatsubai suru", en: "sell, release to market", bn: "বাজারে বিক্রি শুরু করা" },
  { id: 655, lesson: 10, kanji: "うまい", furigana: "うまい", romaji: "umai", en: "taste good, delicious", bn: "সুস্বাদু" },
  { id: 656, lesson: 10, kanji: "いっぱい", furigana: "いっぱい", romaji: "ippai", en: "full, crowded", bn: "ভরপুর / উপচে পড়া" },
  { id: 657, lesson: 10, kanji: "あれ？", furigana: "あれ？", romaji: "are?", en: "What? / Huh?", bn: "একি? / তাই নাকি?" },
  { id: 658, lesson: 10, kanji: "赤ちゃん", furigana: "あかちゃん", romaji: "akachan", en: "baby", bn: "ছোট শিশু / বাচ্চা" },
  { id: 659, lesson: 10, kanji: "あっち", furigana: "あっち", romaji: "acchi", en: "over there (informal)", bn: "ওই দিকে" },
  { id: 660, lesson: 10, kanji: "鉛筆", furigana: "えんぴつ", romaji: "enpitsu", en: "pencil", bn: "পেন্সিল" },
  { id: 661, lesson: 10, kanji: "多く", furigana: "おおく", romaji: "ooku", en: "many, lots of", bn: "অনেক / প্রচুর" },
  { id: 662, lesson: 10, kanji: "お化け屋敷", furigana: "おばけやしき", romaji: "obakeyashiki", en: "haunted house", bn: "ভুতুড়ে বাড়ি" },
  { id: 663, lesson: 10, kanji: "おやき", furigana: "おやき", romaji: "oyaki", en: "oyaki (Nagano dumpling)", bn: "ওয়াকি (নাগানোর ভাজা ডাম্পলিং)" },
  { id: 664, lesson: 10, kanji: "会場", furigana: "かいじょう", romaji: "kaijou", en: "meeting place, conference hall", bn: "অনুষ্ঠানস্থল" },
  { id: 665, lesson: 10, kanji: "カタカナ", furigana: "カタカナ", romaji: "katakana", en: "Japanese katakana script", bn: "কাতাকানা লিপি" },
  { id: 666, lesson: 10, kanji: "工場", furigana: "こうじょう", romaji: "koujou", en: "factory", bn: "কারখানা" },
  { id: 667, lesson: 10, kanji: "国際", furigana: "こくさい", romaji: "kokusai", en: "international", bn: "আন্তর্জাতিক" },
  { id: 668, lesson: 10, kanji: "子ども", furigana: "こども", romaji: "kodomo", en: "child, kid", bn: "বাচ্চা / সন্তান" },
  { id: 669, lesson: 10, kanji: "近所の子ども", furigana: "きんじょのこども", romaji: "kinjo no kodomo", en: "neighborhood child", bn: "পাড়ার বাচ্চা" },
  { id: 670, lesson: 10, kanji: "柔道", furigana: "じゅうどう", romaji: "juudou", en: "judo", bn: "জুডো" },
  { id: 671, lesson: 10, kanji: "世界", furigana: "せかい", romaji: "sekai", en: "world", bn: "বিশ্ব / পৃথিবী" },
  { id: 672, lesson: 10, kanji: "月", furigana: "つき", romaji: "tsuki", en: "moon", bn: "চাঁদ" },
  { id: 673, lesson: 10, kanji: "月を見る", furigana: "つきをみる", romaji: "tsuki o miru", en: "see the moon", bn: "চাঁদ দেখা" },
  { id: 674, lesson: 10, kanji: "電池", furigana: "でんち", romaji: "denchi", en: "battery (dry cell)", bn: "ড্রাই সেল ব্যাটারি" },
  { id: 675, lesson: 10, kanji: "トラ", furigana: "トラ", romaji: "tora", en: "tiger", bn: "বাঘ" },
  { id: 676, lesson: 10, kanji: "博物館", furigana: "はくぶつかん", romaji: "hakubutsukan", en: "museum", bn: "জাদুঘর" },
  { id: 677, lesson: 10, kanji: "プロ", furigana: "プロ", romaji: "puro", en: "pro, professional", bn: "পেশাদার" },
  { id: 678, lesson: 10, kanji: "ミルク", furigana: "ミルク", romaji: "miruku", en: "milk", bn: "দুধ" },
  { id: 679, lesson: 10, kanji: "麦", furigana: "むぎ", romaji: "mugi", en: "wheat, barley, flour", bn: "গম / বার্লি" },
  { id: 680, lesson: 10, kanji: "向こう", furigana: "むこう", romaji: "mukou", en: "over there, opposite side", bn: "ওপাশে / বিপরীত দিক" },
  { id: 681, lesson: 10, kanji: "モデル", furigana: "モデル", romaji: "moderu", en: "model", bn: "মডেল" },
  { id: 682, lesson: 10, kanji: "屋根", furigana: "やね", romaji: "yane", en: "roof", bn: "ছাদ" },
  { id: 683, lesson: 10, kanji: "ヨーロッパ", furigana: "ヨーロッパ", romaji: "yooroppa", en: "Europe", bn: "ইউরোপ" },
  { id: 684, lesson: 10, kanji: "～時代（江戸時代）", furigana: "～じだい（えどじだい）", romaji: "~jidai (edojidai)", en: "~ period (example: Edo period)", bn: "যুগ / কাল (এদো যুগ)" },
  { id: 685, lesson: 10, kanji: "～中（世界中）", furigana: "～じゅう（せかいじゅう）", romaji: "~juu (sekaijuu)", en: "all over ~, throughout ~ (world)", bn: "বিশ্বজুড়ে / সর্বত্র" },
  { id: 686, lesson: 10, kanji: "～箱（弁当箱）", furigana: "～ばこ（べんとうばこ）", romaji: "~bako (bentoubako)", en: "~ box (example: bento box)", bn: "বাক্স (টিফিন বক্স)" },
  { id: 687, lesson: 10, kanji: "行う", furigana: "おこなう", romaji: "okonau", en: "perform, hold", bn: "পরিচালনা করা / সম্পন্ন করা" },
  { id: 688, lesson: 10, kanji: "造る", furigana: "つくる", romaji: "tsukuru", en: "create, build", bn: "নির্মাণ করা / তৈরি করা" },
  { id: 689, lesson: 10, kanji: "開く", furigana: "ひらく", romaji: "hiraku", en: "open, hold", bn: "অনুষ্ঠিত হওয়া / খোলা" },
  { id: 690, lesson: 10, kanji: "コンサートが開かれる", furigana: "コンサートがひらかれる", romaji: "konsaato ga hirakareru", en: "hold a concert", bn: "কনসার্ট অনুষ্ঠিত হওয়া" },
  { id: 691, lesson: 10, kanji: "向かう", furigana: "むかう", romaji: "mukau", en: "leave for, face direction", bn: "রওয়ানা হওয়া / অভিমুখী হওয়া" },
  { id: 692, lesson: 10, kanji: "生きる", furigana: "いきる", romaji: "ikiru", en: "live, to be alive", bn: "বেঁচে থাকা" },
  { id: 693, lesson: 10, kanji: "生まれる", furigana: "うまれる", romaji: "umareru", en: "be born", bn: "জন্মগ্রহণ করা" },
  { id: 694, lesson: 10, kanji: "建てる", furigana: "たてる", romaji: "tateru", en: "build", bn: "ভবন তৈরি করা" },
  { id: 695, lesson: 10, kanji: "逃げる", furigana: "にげる", romaji: "nigeru", en: "run away, escape", bn: "পালিয়ে যাওয়া" },
  { id: 696, lesson: 10, kanji: "設計・する", furigana: "せっけいする", romaji: "sekkei suru", en: "design, plan", bn: "নকশা করা" },
  { id: 697, lesson: 10, kanji: "発見・する", furigana: "はっけんする", romaji: "hakken suru", en: "find, discover", bn: "আবিষ্কার করা" },
  { id: 698, lesson: 10, kanji: "発明・する", furigana: "はつめいする", romaji: "hatsumei suru", en: "invent", bn: "উদ্ভাবন করা" },
  { id: 699, lesson: 10, kanji: "～によって", furigana: "～によって", romaji: "~ ni yotte", en: "due to ~, by", bn: "কারণে / মাধ্যমে" },
  { id: 700, lesson: 10, kanji: "遠く", furigana: "とおく", romaji: "tooku", en: "far away", bn: "বহুদূরে" },
  { id: 701, lesson: 10, kanji: "乗り場", furigana: "のりば", romaji: "noriba", en: "platform, loading zone", bn: "গাড়িতে ওঠার স্থান" },
  { id: 702, lesson: 10, kanji: "ロープウエー", furigana: "ロープウエー", romaji: "roopuwee", en: "ropeway, cable car", bn: "ক্যাবল কার" },
  { id: 703, lesson: 10, kanji: "ちょうど", furigana: "ちょうど", romaji: "choudo", en: "exactly, precisely", bn: "ঠিক ঠিক / পুরোপুরি" },
  { id: 704, lesson: 10, kanji: "お待たせ", furigana: "おまたせ", romaji: "omatase", en: "\"Sorry to keep you waiting\"", bn: "দেরি করানোর জন্য দুঃখিত" },

  // LESSON 11: 地域社会の中で (In the Local Community)
  { id: 705, lesson: 11, kanji: "おじさん", furigana: "おじさん", romaji: "ojisan", en: "uncle, mister (middle-aged men)", bn: "চাচা / মধ্যবয়সী ব্যক্তি" },
  { id: 706, lesson: 11, kanji: "苦労", furigana: "くろう", romaji: "kurou", en: "trouble, burden, hardship", bn: "কষ্ট / ভোগান্তি" },
  { id: 707, lesson: 11, kanji: "八百屋", furigana: "やおや", romaji: "yaoya", en: "vegetable vendor, green grocery", bn: "সবজি বিক্রেতা" },
  { id: 708, lesson: 11, kanji: "話しかける", furigana: "はなしかける", romaji: "hanashikakeru", en: "talk to, speak to", bn: "যেচে কথা বলা" },
  { id: 709, lesson: 11, kanji: "親しい", furigana: "したしい", romaji: "shitashii", en: "familiar, intimate", bn: "ঘনিষ্ঠ / অন্তরঙ্গ" },
  { id: 710, lesson: 11, kanji: "何度も", furigana: "なんども", romaji: "nandomo", en: "over and over again, many times", bn: "বারবার / বহুবার" },
  { id: 711, lesson: 11, kanji: "彼女", furigana: "かのじょ", romaji: "kanojo", en: "girlfriend", bn: "প্রেমিকা" },
  { id: 712, lesson: 11, kanji: "彼", furigana: "かれ", romaji: "kare", en: "boyfriend", bn: "প্রেমিক" },
  { id: 713, lesson: 11, kanji: "国の彼女／彼に会いたい", furigana: "くにのかのじょ／かれにあいたい", romaji: "kuni no kanojo/kare ni aitai", en: "\"I miss my partner back home\"", bn: "দেশের সঙ্গীর সাথে দেখা করতে মন চায়" },
  { id: 714, lesson: 11, kanji: "記者", furigana: "きしゃ", romaji: "kisha", en: "journalist, reporter", bn: "সাংবাদিক" },
  { id: 715, lesson: 11, kanji: "興味", furigana: "きょうみ", romaji: "kyoumi", en: "interest", bn: "আগ্রহ" },
  { id: 716, lesson: 11, kanji: "敬語", furigana: "けいご", romaji: "keigo", en: "respectful language", bn: "মার্জিত সম্মানসূচক ভাষা" },
  { id: 717, lesson: 11, kanji: "こと", furigana: "こと", romaji: "koto", en: "matters about ~, things about ~", bn: "বিষয় / ব্যাপার" },
  { id: 718, lesson: 11, kanji: "将来のこと", furigana: "しょうらいのこと", romaji: "shourai no koto", en: "things about the future", bn: "ভবিষ্যতের ব্যাপার" },
  { id: 719, lesson: 11, kanji: "地域", furigana: "ちいき", romaji: "chiiki", en: "region, area, zone, locality", bn: "এলাকা / অঞ্চল" },
  { id: 720, lesson: 11, kanji: "違い", furigana: "ちがい", romaji: "chigai", en: "difference", bn: "পার্থক্য" },
  { id: 721, lesson: 11, kanji: "物価", furigana: "ぶっか", romaji: "bukka", en: "prices of commodities", bn: "দ্রব্যমূল্য" },
  { id: 722, lesson: 11, kanji: "文化", furigana: "ぶんか", romaji: "bunka", en: "culture", bn: "সংস্কৃতি" },
  { id: 723, lesson: 11, kanji: "ボランティア", furigana: "ボランティア", romaji: "borantia", en: "volunteer", bn: "স্বেচ্ছাসেবী" },
  { id: 724, lesson: 11, kanji: "無理", furigana: "むり", romaji: "muri", en: "overdo, take something too far", bn: "সাধ্যের বাইরে / অসম্ভব" },
  { id: 725, lesson: 11, kanji: "～代（食事代）", furigana: "～だい（しょくじだい）", romaji: "~dai (shokujidai)", en: "~ charges, fees (dining charges)", bn: "খরচ (খাবারের বিল)" },
  { id: 726, lesson: 11, kanji: "持つ", furigana: "もつ", romaji: "motsu", en: "have, hold", bn: "থাকা / রাখা" },
  { id: 727, lesson: 11, kanji: "興味を持つ", furigana: "きょうみをもつ", romaji: "kyoumi o motsu", en: "have an interest", bn: "আগ্রহ বোধ করা" },
  { id: 728, lesson: 11, kanji: "学ぶ", furigana: "まなぶ", romaji: "manabu", en: "learn, study", bn: "জ্ঞানার্জন করা / শেখা" },
  { id: 729, lesson: 11, kanji: "折れる", furigana: "おれる", romaji: "oreru", en: "break, snap", bn: "ভেঙে যাওয়া" },
  { id: 730, lesson: 11, kanji: "答える", furigana: "こたえる", romaji: "kotaeru", en: "answer, respond", bn: "উত্তর দেওয়া" },
  { id: 731, lesson: 11, kanji: "育てる", furigana: "そだてる", romaji: "sodateru", en: "raise (a child), bring up", bn: "লালন-পালন করা" },
  { id: 732, lesson: 11, kanji: "インタビュー・する", furigana: "インタビューする", romaji: "intabyuu suru", en: "interview", bn: "সাক্ষাৎকার নেওয়া" },
  { id: 733, lesson: 11, kanji: "外食・する", furigana: "がいしょくする", romaji: "gaishoku suru", en: "dine out, eat out", bn: "বাইরে খাওয়া" },
  { id: 734, lesson: 11, kanji: "研究・する", furigana: "けんきゅうする", romaji: "kenkyuu suru", en: "research", bn: "গবেষণা করা" },
  { id: 735, lesson: 11, kanji: "故障・する", furigana: "こしょうする", romaji: "koshou suru", en: "get out of order, break down", bn: "নষ্ট / বিকল হওয়া" },
  { id: 736, lesson: 11, kanji: "節約・する", furigana: "せつやくする", romaji: "setsuyaku suru", en: "economize, be thrifty", bn: "মিতব্যয়ী হওয়া / সাশ্রয় করা" },
  { id: 737, lesson: 11, kanji: "あんまり", furigana: "あんまり", romaji: "anmari", en: "not much, not very", bn: "তেমন একটা না" },
  { id: 738, lesson: 11, kanji: "だいたい", furigana: "だいたい", romaji: "daitai", en: "mostly, most of the time", bn: "প্রায় / বেশিরভাগ ক্ষেত্রে" },
  { id: 739, lesson: 11, kanji: "運転手", furigana: "うんてんしゅ", romaji: "untenshu", en: "driver", bn: "চালক / ড্রাইভার" },
  { id: 740, lesson: 11, kanji: "駅前", furigana: "えきまえ", romaji: "ekimae", en: "in front of the train station", bn: "স্টেশনের সামনে" },
  { id: 741, lesson: 11, kanji: "具合", furigana: "ぐあい", romaji: "guai", en: "condition, health", bn: "শারীরিক অবস্থা" },
  { id: 742, lesson: 11, kanji: "今夜", furigana: "こんや", romaji: "konya", en: "tonight", bn: "আজ রাতে" },
  { id: 743, lesson: 11, kanji: "打つ", furigana: "うつ", romaji: "utsu", en: "hit", bn: "আঘাত করা / মারা" },
  { id: 744, lesson: 11, kanji: "回る", furigana: "まわる", romaji: "mawaru", en: "go around", bn: "ঘোরা / পাক খাওয়া" },
  { id: 745, lesson: 11, kanji: "諦める", furigana: "あきらめる", romaji: "akirameru", en: "give up", bn: "হাল ছেড়ে দেওয়া" },
  { id: 746, lesson: 11, kanji: "投げる", furigana: "なげる", romaji: "nageru", en: "throw", bn: "ছুঁড়ে মারা" },
  { id: 747, lesson: 11, kanji: "出張・する", furigana: "しゅっちょうする", romaji: "shucchou suru", en: "go on a business trip", bn: "অফিসিয়াল সফরে যাওয়া" },
  { id: 748, lesson: 11, kanji: "機会", furigana: "きかい", romaji: "kikai", en: "chance, opportunity", bn: "সুযোগ" },
  { id: 749, lesson: 11, kanji: "地域", furigana: "ちいき", romaji: "chiiki", en: "area, region", bn: "অঞ্চল / এলাকা" },
  { id: 750, lesson: 11, kanji: "～君", furigana: "～くん", romaji: "~kun", en: "suffix for boy's names", bn: "ছেলেদের নামের শেষে সম্বোধন" },
  { id: 751, lesson: 11, kanji: "シュート・する", furigana: "シュートする", romaji: "shuuto suru", en: "shoot (ball)", bn: "শট নেওয়া" },
  { id: 752, lesson: 11, kanji: "お帰りなさい", furigana: "おかえりなさい", romaji: "okaerinasai", en: "\"Welcome home.\"", bn: "ফিরে আসায় স্বাগতম" },
  { id: 753, lesson: 11, kanji: "よし", furigana: "よし", romaji: "yoshi", en: "good, come on", bn: "বেশ! / শাবাশ!" },

  // LESSON 12: 私の健康法 (My Health Method)
  { id: 754, lesson: 12, kanji: "インスタント", furigana: "インスタント", romaji: "insutanto", en: "instant", bn: "তাৎক্ষণিক" },
  { id: 755, lesson: 12, kanji: "食品", furigana: "しょくひん", romaji: "shokuhin", en: "food products", bn: "খাদ্যদ্রব্য" },
  { id: 756, lesson: 12, kanji: "残す", furigana: "のこす", romaji: "nokosu", en: "leave, save", bn: "অবশিষ্ট রাখা / বাঁচানো" },
  { id: 757, lesson: 12, kanji: "残る", furigana: "のこる", romaji: "nokoru", en: "be left remaining", bn: "অবশিষ্ট থাকা" },
  { id: 758, lesson: 12, kanji: "冷凍・する", furigana: "れいとうする", romaji: "reitou suru", en: "freeze", bn: "বরফে জমিয়ে রাখা" },
  { id: 759, lesson: 12, kanji: "胃", furigana: "い", romaji: "i", en: "stomach", bn: "পাকস্থলী" },
  { id: 760, lesson: 12, kanji: "痛み", furigana: "いたみ", romaji: "itami", en: "pain", bn: "ব্যথা" },
  { id: 761, lesson: 12, kanji: "うがい", furigana: "うがい", romaji: "ugai", en: "gargling", bn: "কুলকুচি / গার্গল" },
  { id: 762, lesson: 12, kanji: "元気", furigana: "げんき", romaji: "genki", en: "healthy, lively, spirited", bn: "সুস্থ / সতেজ" },
  { id: 763, lesson: 12, kanji: "氷", furigana: "こおり", romaji: "koori", en: "ice", bn: "বরফ" },
  { id: 764, lesson: 12, kanji: "湿布", furigana: "しっぷ", romaji: "shippu", en: "cold (hot) compress", bn: "ব্যথানাশক ব্যান্ডেজ / পট্টি" },
  { id: 765, lesson: 12, kanji: "ジム", furigana: "ジム", romaji: "jimu", en: "gym, gymnasium", bn: "ব্যায়ামাগার / জিম" },
  { id: 766, lesson: 12, kanji: "疲れ", furigana: "つかれ", romaji: "tsukare", en: "fatigue, tiredness", bn: "ক্লান্তি" },
  { id: 767, lesson: 12, kanji: "ドレッシング", furigana: "ドレッシング", romaji: "doresshingu", en: "salad dressing", bn: "সালাদের ড্রেসিং" },
  { id: 768, lesson: 12, kanji: "様子", furigana: "ようす", romaji: "yousu", en: "appearance, state", bn: "শারীরিক অবস্থা" },
  { id: 769, lesson: 12, kanji: "～金（入会金）", furigana: "～きん（にゅうかいきん）", romaji: "~kin (nyuukaikin)", en: "~ fee (admission fee)", bn: "ফি (ভর্তি ফি)" },
  { id: 770, lesson: 12, kanji: "さす", furigana: "さす", romaji: "sasu", en: "hold over one's head", bn: "মাথার উপরে ধরা" },
  { id: 771, lesson: 12, kanji: "傘をさす", furigana: "かさをさす", romaji: "kasa o sasu", en: "open an umbrella", bn: "ছাতা ধরা" },
  { id: 772, lesson: 12, kanji: "酔う", furigana: "よう", romaji: "you", en: "get drunk, feel sick (stomach)", bn: "নেশাগ্রস্ত হওয়া / বমি বমি লাগা" },
  { id: 773, lesson: 12, kanji: "取れる", furigana: "とれる", romaji: "toreru", en: "relieve, break free from", bn: "দূর হওয়া / কমে যাওয়া" },
  { id: 774, lesson: 12, kanji: "アドバイス・する", furigana: "アドバイスする", romaji: "adobaisu suru", en: "give advice", bn: "পরামর্শ দেওয়া" },
  { id: 775, lesson: 12, kanji: "入会・する", furigana: "にゅうかいする", romaji: "nyuukai suru", en: "join, become a member", bn: "সদস্য হওয়া" },
  { id: 776, lesson: 12, kanji: "ガンガン", furigana: "ガンガン", romaji: "gangan", en: "pounding, throbbing (headache)", bn: "মাথা দপদপ করা" },
  { id: 777, lesson: 12, kanji: "パンパン", furigana: "パンパン", romaji: "panpan", en: "tense, full muscles", bn: "পেশি টানটান ও শক্ত হওয়া" },
  { id: 778, lesson: 12, kanji: "フラフラ", furigana: "フラフラ", romaji: "furafura", en: "dizzy, groggy, unsteady", bn: "মাথা ঘোরা / টলমল করা" },
  { id: 779, lesson: 12, kanji: "ムカムカ", furigana: "ムカムカ", romaji: "mukamuka", en: "nauseous, queasy", bn: "বমি বমি ভাব হওয়া" },
  { id: 780, lesson: 12, kanji: "栄養", furigana: "えいよう", romaji: "eiyou", en: "nutrition", bn: "পুষ্টি" },
  { id: 781, lesson: 12, kanji: "肩", furigana: "かた", romaji: "kata", en: "shoulder", bn: "কাঁধ" },
  { id: 782, lesson: 12, kanji: "首", furigana: "くび", romaji: "kubi", en: "neck", bn: "ঘাড়" },
  { id: 783, lesson: 12, kanji: "カロリー", furigana: "カロリー", romaji: "karorii", en: "calorie", bn: "ক্যালোরি" },
  { id: 784, lesson: 12, kanji: "健康", furigana: "けんこう", romaji: "kenkou", en: "health, fitness", bn: "স্বাস্থ্য" },
  { id: 785, lesson: 12, kanji: "この頃", furigana: "このごろ", romaji: "konogoro", en: "these days, nowadays", bn: "ইদানীং" },
  { id: 786, lesson: 12, kanji: "ジューサー", furigana: "ジューサー", romaji: "juusaa", en: "juicer", bn: "জুসার মেশিন" },
  { id: 787, lesson: 12, kanji: "ショウガ", furigana: "ショウガ", romaji: "shouga", en: "ginger", bn: "আদা" },
  { id: 788, lesson: 12, kanji: "ストレス", furigana: "ストレス", romaji: "sutoresu", en: "stress", bn: "মানসিক চাপ" },
  { id: 789, lesson: 12, kanji: "体脂肪", furigana: "たいしぼう", romaji: "taishibou", en: "body fat", bn: "শরীরের চর্বি" },
  { id: 790, lesson: 12, kanji: "ネックストレッチャー", furigana: "ネックストレッチャー", romaji: "nekku sutorecchaa", en: "neck brace, neck collar", bn: "ঘাড়ের ব্যায়ামের বেল্ট" },
  { id: 791, lesson: 12, kanji: "バランス", furigana: "バランス", romaji: "baransu", en: "balance", bn: "ভারসাম্য" },
  { id: 792, lesson: 12, kanji: "ビタミンC", furigana: "ビタミンシー", romaji: "bitamin shii", en: "vitamin C", bn: "ভিটামিন সি" },
  { id: 793, lesson: 12, kanji: "ヘルスケア", furigana: "ヘルスケア", romaji: "herusukea", en: "healthcare, fitness", bn: "স্বাস্থ্যসেবা" },
  { id: 794, lesson: 12, kanji: "マッサージ器", furigana: "マッサージき", romaji: "massaaji ki", en: "massage machine", bn: "ম্যাসাজ করার যন্ত্র" },
  { id: 795, lesson: 12, kanji: "～計（温度計）", furigana: "～けい（おんどけい）", romaji: "~kei (ondokei)", en: "~ meter (example: thermometer)", bn: "মাপক যন্ত্র (থার্মোমিটার)" },
  { id: 796, lesson: 12, kanji: "～不足（運動不足）", furigana: "～ぶそく（うんどうぶそく）", romaji: "~busoku (undoubusoku)", en: "deficiency in ~ (lack of exercise)", bn: "ঘাটতি (ব্যায়ামের অভাব)" },
  { id: 797, lesson: 12, kanji: "～率（出席率）", furigana: "～りつ（しゅっせきりつ）", romaji: "~ritsu (shussekiritsu)", en: "~ rate (attendance rate)", bn: "হার (উপস্থিতির হার)" },
  { id: 798, lesson: 12, kanji: "動かす", furigana: "うごかす", romaji: "ugokasu", en: "move, set in motion", bn: "নাড়াচাড়া করা" },
  { id: 799, lesson: 12, kanji: "こる", furigana: "こる", romaji: "koru", en: "become stiff", bn: "পেশি শক্ত হয়ে যাওয়া" },
  { id: 800, lesson: 12, kanji: "たまる", furigana: "たまる", romaji: "tamaru", en: "build up, accumulate", bn: "জমে থাকা" },
  { id: 801, lesson: 12, kanji: "取る", furigana: "とる", romaji: "toru", en: "break free from, relieve", bn: "দূর করা" },
  { id: 802, lesson: 12, kanji: "疲れを取る", furigana: "つかれをとる", romaji: "tsukare o toru", en: "relieve one's fatigue", bn: "ক্লান্তি দূর করা" },
  { id: 803, lesson: 12, kanji: "眠る", furigana: "ねむる", romaji: "nemuru", en: "sleep", bn: "ঘুমানো" },
  { id: 804, lesson: 12, kanji: "測る", furigana: "はかる", romaji: "hakaru", en: "measure", bn: "মাপা" },
  { id: 805, lesson: 12, kanji: "太る", furigana: "ふとる", romaji: "futoru", en: "gain weight, get fat", bn: "মোটা হওয়া" },
  { id: 806, lesson: 12, kanji: "痩せる", furigana: "やせる", romaji: "yaseru", en: "lose weight, become thin", bn: "চিকন / রোগা হওয়া" },
  { id: 807, lesson: 12, kanji: "冷える", furigana: "ひえる", romaji: "hieru", en: "chill, get cold", bn: "ঠান্ডা হয়ে যাওয়া" },
  { id: 808, lesson: 12, kanji: "計算・する", furigana: "けいさんする", romaji: "keisan suru", en: "calculate", bn: "গণনা করা" },
  { id: 809, lesson: 12, kanji: "ダイエット・する", furigana: "ダイエットする", romaji: "daietto suru", en: "diet", bn: "ডায়েট করা" },
  { id: 810, lesson: 12, kanji: "マッサージ・する", furigana: "マッサージする", romaji: "massaaji suru", en: "massage", bn: "ম্যাসাজ করা" },
  { id: 811, lesson: 12, kanji: "キャラクター", furigana: "キャラクター", romaji: "kyarakutaa", en: "character, personality", bn: "চরিত্র" },
  { id: 812, lesson: 12, kanji: "グレープフルーツ", furigana: "グレープフルーツ", romaji: "gureepufuruutsu", en: "grapefruit", bn: "জাম্বুরা / বাতাবিলেবু" },
  { id: 813, lesson: 12, kanji: "二日酔い", furigana: "ふつかよい", romaji: "futsukayoi", en: "hangover", bn: "মদপানের পরের মাথাব্যথা" },
  { id: 814, lesson: 12, kanji: "管理・する", furigana: "かんりする", romaji: "kanri suru", en: "manage, administer", bn: "পরিচালনা বা তত্ত্বাবধান করা" },
  { id: 815, lesson: 12, kanji: "成長・する", furigana: "せいちょうする", romaji: "seichou suru", en: "grow, develop", bn: "বেড়ে ওঠা / বৃদ্ধি" },
  { id: 816, lesson: 12, kanji: "気にする", furigana: "きにする", romaji: "ki ni suru", en: "feel uneasy, worry about", bn: "মনে নেওয়া / পাত্তা দেওয়া" },
  { id: 817, lesson: 12, kanji: "気をつける", furigana: "きをつける", romaji: "ki o tsukeru", en: "be careful", bn: "সাবধান থাকা" },
  { id: 818, lesson: 12, kanji: "ほとんど", furigana: "ほとんど", romaji: "hotondo", en: "hardly, mostly", bn: "প্রায় সব" },
  { id: 819, lesson: 12, kanji: "～とも", furigana: "～とも", romaji: "~tomo", en: "both", bn: "উভয়ই" },

  // LESSON 13: 親の気持ち・子の気持ち (Parents' & Children's Feelings)
  { id: 820, lesson: 13, kanji: "自然", furigana: "しぜん", romaji: "shizen", en: "nature", bn: "প্রকৃতি" },
  { id: 821, lesson: 13, kanji: "釣る", furigana: "つる", romaji: "tsuru", en: "fish", bn: "মাছ ধরা" },
  { id: 822, lesson: 13, kanji: "手に入れる", furigana: "てにいれる", romaji: "te ni ireru", en: "obtain, acquire", bn: "অর্জন করা / পাওয়া" },
  { id: 823, lesson: 13, kanji: "不利（な）", furigana: "ふり（な）", romaji: "furi (na)", en: "disadvantageous", bn: "অসুবিধাজনক / প্রতিকূল" },
  { id: 824, lesson: 13, kanji: "男の子", furigana: "おとこのこ", romaji: "otoko no ko", en: "boy", bn: "ছেলে শিশু" },
  { id: 825, lesson: 13, kanji: "親", furigana: "おや", romaji: "oya", en: "parent", bn: "অভিভাবক / পিতামাতা" },
  { id: 826, lesson: 13, kanji: "父親", furigana: "ちちおや", romaji: "chichioya", en: "father", bn: "বাবা" },
  { id: 827, lesson: 13, kanji: "母親", furigana: "ははおや", romaji: "hahaoya", en: "mother", bn: "মা" },
  { id: 828, lesson: 13, kanji: "家事", furigana: "かじ", romaji: "kaji", en: "housework", bn: "গৃহস্থালির কাজ" },
  { id: 829, lesson: 13, kanji: "ゲームセンター", furigana: "ゲームセンター", romaji: "geemu sentaa", en: "game arcade", bn: "ভিডিও গেম খেলার জায়গা" },
  { id: 830, lesson: 13, kanji: "コーチ", furigana: "コーチ", romaji: "kouchi", en: "coach", bn: "কোচ / প্রশিক্ষক" },
  { id: 831, lesson: 13, kanji: "頃", furigana: "ころ", romaji: "koro", en: "when I was ~", bn: "সেই সময়" },
  { id: 832, lesson: 13, kanji: "塾", furigana: "じゅく", romaji: "juku", en: "after-school cram school", bn: "কোচিং সেন্টার" },
  { id: 833, lesson: 13, kanji: "数学", furigana: "すうがく", romaji: "suugaku", en: "mathematics, math", bn: "গণিত" },
  { id: 834, lesson: 13, kanji: "～キロ", furigana: "～キロ", romaji: "~kiro", en: "~ kilometers, ~ kilograms", bn: "কিলোমিটার / কিলোগ্রাম" },
  { id: 835, lesson: 13, kanji: "～ずつ（20個ずつ）", furigana: "～ずつ（にじゅっこずつ）", romaji: "~zutsu (nijukkozutsu)", en: "~ each (e.g. 20 each)", bn: "করে (২০টি করে)" },
  { id: 836, lesson: 13, kanji: "騒ぐ", furigana: "さわぐ", romaji: "sawagu", en: "be noisy, act up", bn: "হইচই করা" },
  { id: 837, lesson: 13, kanji: "世話・する", furigana: "せわする", romaji: "sewa suru", en: "take care of", bn: "যত্ন নেওয়া / দেখাশোনা করা" },
  { id: 838, lesson: 13, kanji: "偉い", furigana: "えらい", romaji: "erai", en: "great, excellent, well done", bn: "মহৎ / প্রশংসনীয়" },
  { id: 839, lesson: 13, kanji: "自由（な）", furigana: "じゆう（な）", romaji: "jiyuu (na)", en: "free, at will", bn: "স্বাধীন" },
  { id: 840, lesson: 13, kanji: "必ず", furigana: "かならず", romaji: "kanarazu", en: "by all means, certainly", bn: "অবশ্যই" },
  { id: 841, lesson: 13, kanji: "やっぱり", furigana: "やっぱり", romaji: "yappari", en: "after all, as expected", bn: "যেমনটা ভেবেছিলাম / শেষমেশ" },
  { id: 842, lesson: 13, kanji: "遅くまで", furigana: "おそくまで", romaji: "osoku made", en: "until late", bn: "গভীর রাত পর্যন্ত" },
  { id: 843, lesson: 13, kanji: "海外", furigana: "かいがい", romaji: "kaigai", en: "overseas", bn: "বিদেশ" },
  { id: 844, lesson: 13, kanji: "教育", furigana: "きょういく", romaji: "kyouiku", en: "education", bn: "শিক্ষা" },
  { id: 845, lesson: 13, kanji: "曲", furigana: "きょく", romaji: "kyoku", en: "song track, melody", bn: "সুর / গান" },
  { id: 846, lesson: 13, kanji: "化粧品", furigana: "けしょうひん", romaji: "keshouhin", en: "cosmetics", bn: "প্রসাধন সামগ্রী" },
  { id: 847, lesson: 13, kanji: "手伝い", furigana: "てつだい", romaji: "tetsudai", en: "help, assistance, assistant", bn: "সাহায্য / সাহায্যকারী" },
  { id: 848, lesson: 13, kanji: "習い事", furigana: "ならいごと", romaji: "naraigoto", en: "lessons (violin, ballet, etc.)", bn: "শখের শিক্ষা (গান/নাচ ইত্যাদি)" },
  { id: 849, lesson: 13, kanji: "～会（発表会）", furigana: "～かい（はっぴょうかい）", romaji: "~kai (happyoukai)", en: "~ recital, presentation meeting", bn: "প্রদর্শনী অনুষ্ঠান" },
  { id: 850, lesson: 13, kanji: "叱る", furigana: "しかる", romaji: "shikaru", en: "scold", bn: "বকা দেওয়া / শাসন করা" },
  { id: 851, lesson: 13, kanji: "泣く", furigana: "なく", romaji: "naku", en: "cry", bn: "কান্না করা" },
  { id: 852, lesson: 13, kanji: "残す", furigana: "のこす", romaji: "nokosu", en: "leave, save", bn: "ফেলে রাখা" },
  { id: 853, lesson: 13, kanji: "やる", furigana: "やる", romaji: "yaru", en: "do", bn: "করা" },
  { id: 854, lesson: 13, kanji: "宿題をやる", furigana: "しゅくだいをやる", romaji: "shukudai o yaru", en: "do my homework", bn: "হোমওয়ার্ক করা" },
  { id: 855, lesson: 13, kanji: "褒める", furigana: "ほめる", romaji: "homeru", en: "praise", bn: "প্রশংসা করা" },
  { id: 856, lesson: 13, kanji: "やめる", furigana: "やめる", romaji: "yameru", en: "quit, stop, give up", bn: "ছেড়ে দেওয়া / বন্ধ করা" },
  { id: 857, lesson: 13, kanji: "発表・する", furigana: "はっぴょうする", romaji: "happyou suru", en: "announce, present", bn: "উপস্থাপন করা" },
  { id: 858, lesson: 13, kanji: "厳しい", furigana: "きびしい", romaji: "kibishii", en: "strict, severe", bn: "কঠোর" },
  { id: 859, lesson: 13, kanji: "嫌（な）", furigana: "いや（な）", romaji: "iya (na)", en: "disagreeable, unpleasant", bn: "বিরক্তিকর / অপছন্দনীয়" },
  { id: 860, lesson: 13, kanji: "熱心（な）", furigana: "ねっしん（な）", romaji: "nesshin (na)", en: "eager, enthusiastic, devoted", bn: "আন্তরিক / মনোযোগী" },
  { id: 861, lesson: 13, kanji: "何でも", furigana: "なんでも", romaji: "nandemo", en: "anything", bn: "যেকোনো কিছু" },
  { id: 862, lesson: 13, kanji: "おもちゃ", furigana: "おもちゃ", romaji: "omocha", en: "toy", bn: "খেলনা" },
  { id: 863, lesson: 13, kanji: "祖母", furigana: "そぼ", romaji: "sobo", en: "grandmother", bn: "দাদি / নানি" },
  { id: 864, lesson: 13, kanji: "僕", furigana: "ぼく", romaji: "boku", en: "I, me (informal male)", bn: "আমি (ছেলেদের কথ্য)" },
  { id: 865, lesson: 13, kanji: "役に立つ", furigana: "やくにたつ", romaji: "yaku ni tatsu", en: "be useful", bn: "কাজে লাগা / উপযোগী হওয়া" },
  { id: 866, lesson: 13, kanji: "ちゃんと", furigana: "ちゃんと", romaji: "chanto", en: "properly", bn: "ঠিকঠাক / যথাযথভাবে" },
  { id: 867, lesson: 13, kanji: "仕方がない", furigana: "しかたがない", romaji: "shikata ga nai", en: "no choice, have no alternative", bn: "আর কোনো উপায় নেই" },

  // LESSON 14: イベント・行事 (Events & Customs)
  { id: 868, lesson: 14, kanji: "作品", furigana: "さくひん", romaji: "sakuhin", en: "work (picture/painting, etc.)", bn: "শিল্পকর্ম" },
  { id: 869, lesson: 14, kanji: "奨学金", furigana: "しょうがくきん", romaji: "shougakukin", en: "scholarship", bn: "বৃত্তি" },
  { id: 870, lesson: 14, kanji: "漫画家", furigana: "まんがか", romaji: "mangaka", en: "cartoonist, manga artist", bn: "মাঙ্গা চিত্রশিল্পী" },
  { id: 871, lesson: 14, kanji: "～部", furigana: "～ぶ", romaji: "~bu", en: "~ department, ~ section", bn: "বিভাগ / ক্লাব" },
  { id: 872, lesson: 14, kanji: "活動・する", furigana: "かつどうする", romaji: "katsudou suru", en: "be active, operate", bn: "কার্যক্রম চালানো" },
  { id: 873, lesson: 14, kanji: "支援・する", furigana: "しえんする", romaji: "shien suru", en: "support", bn: "সহায়তা করা" },
  { id: 874, lesson: 14, kanji: "ヒット・する", furigana: "ヒットする", romaji: "hitto suru", en: "be a hit", bn: "জনপ্রিয় / হিট হওয়া" },
  { id: 875, lesson: 14, kanji: "放送・する", furigana: "ほうそうする", romaji: "housou suru", en: "broadcast, air", bn: "সম্প্রচার করা" },
  { id: 876, lesson: 14, kanji: "連載・する", furigana: "れんさいする", romaji: "rensai suru", en: "appear serially in publication", bn: "ধারাবাহিকভাবে প্রকাশ করা" },
  { id: 877, lesson: 14, kanji: "素晴らしい", furigana: "すばらしい", romaji: "subarashii", en: "magnificent, incredible", bn: "চমৎকার / অসাধারণ" },
  { id: 878, lesson: 14, kanji: "メジャー（な）", furigana: "メジャー（な）", romaji: "mejaa (na)", en: "major", bn: "প্রধান / মূলধারার" },
  { id: 879, lesson: 14, kanji: "遊び", furigana: "あそび", romaji: "asobi", en: "game, play", bn: "খেলাধুলা" },
  { id: 880, lesson: 14, kanji: "ウナギ", furigana: "ウナギ", romaji: "unagi", en: "eel", bn: "ঈল মাছ" },
  { id: 881, lesson: 14, kanji: "大勢", furigana: "おおぜい", romaji: "oozei", en: "crowd, in large numbers", bn: "বহু লোক" },
  { id: 882, lesson: 14, kanji: "おせち料理", furigana: "おせちりょうり", romaji: "osechi ryouri", en: "traditional New Year's food", bn: "ওসেচি (জাপানি নববর্ষের খাবার)" },
  { id: 883, lesson: 14, kanji: "おもちゃ", furigana: "おもちゃ", romaji: "omocha", en: "toy", bn: "খেলনা" },
  { id: 884, lesson: 14, kanji: "女の子", furigana: "おんなのこ", romaji: "onna no ko", en: "girl", bn: "মেয়ে শিশু" },
  { id: 885, lesson: 14, kanji: "数", furigana: "かず", romaji: "kazu", en: "number", bn: "সংখ্যা" },
  { id: 886, lesson: 14, kanji: "（お）金持ち", furigana: "（お）かねもち", romaji: "(o)kanemochi", en: "rich person", bn: "ধনী ব্যক্তি" },
  { id: 887, lesson: 14, kanji: "カボチャ", furigana: "カボチャ", romaji: "kabocha", en: "pumpkin", bn: "মিষ্টি কুমড়া" },
  { id: 888, lesson: 14, kanji: "空手", furigana: "からて", romaji: "karate", en: "karate", bn: "কারাতে" },
  { id: 889, lesson: 14, kanji: "ギョーザ", furigana: "ギョーザ", romaji: "gyouza", en: "dumpling, potstickers", bn: "গিওজা ডাম্পলিং" },
  { id: 890, lesson: 14, kanji: "行事", furigana: "ぎょうじ", romaji: "gyouji", en: "event, occasion", bn: "বাৎসরিক আচার / উৎসব" },
  { id: 891, lesson: 14, kanji: "大みそか", furigana: "おおみそか", romaji: "oomisoka", en: "New Year's Eve", bn: "বছরের শেষ দিন" },
  { id: 892, lesson: 14, kanji: "お盆", furigana: "おぼん", romaji: "obon", en: "Obon festival", bn: "ওবোন উৎসব" },
  { id: 893, lesson: 14, kanji: "敬老の日", furigana: "けいろうのひ", romaji: "keirou no hi", en: "Respect-for-the-Aged Day", bn: "প্রবীণ সম্মাননা দিবস" },
  { id: 894, lesson: 14, kanji: "七五三", furigana: "しちごさん", romaji: "shichigosan", en: "Seven-Five-Three Festival", bn: "শিচিগোসান উৎসব" },
  { id: 895, lesson: 14, kanji: "（お）正月", furigana: "（お）しょうがつ", romaji: "(o)shougatsu", en: "New Year's holidays", bn: "নববর্ষের ছুটি" },
  { id: 896, lesson: 14, kanji: "成人の日", furigana: "せいじんのひ", romaji: "seijin no hi", en: "Coming of Age Day", bn: "প্রাপ্তবয়স্ক দিবস" },
  { id: 897, lesson: 14, kanji: "節分", furigana: "せつぶん", romaji: "setsubun", en: "bean-throwing day (end of winter)", bn: "সেতসুবুন উৎসব" },
  { id: 898, lesson: 14, kanji: "冬至", furigana: "とうじ", romaji: "touji", en: "winter solstice", bn: "বছরের ক্ষুদ্রতম দিন" },
  { id: 899, lesson: 14, kanji: "土用の丑の日", furigana: "どようのうしのひ", romaji: "doyou no ushi no hi", en: "Midsummer Day of the Ox", bn: "গ্রীষ্মের বিশেষ ঈল মাছ খাওয়ার দিন" },
  { id: 900, lesson: 14, kanji: "ひなまつり", furigana: "ひなまつり", romaji: "hinamatsuri", en: "Doll Festival", bn: "মেয়েদের পুতুল উৎসব" },
  { id: 901, lesson: 14, kanji: "ごちそう", furigana: "ごちそう", romaji: "gochisou", en: "big meal, feast", bn: "সুস্বাদু ভূরিভোজ" },
  { id: 902, lesson: 14, kanji: "新年", furigana: "しんねん", romaji: "shinnen", en: "New Year's Day", bn: "নতুন বছর" },
  { id: 903, lesson: 14, kanji: "将棋", furigana: "しょうぎ", romaji: "shougi", en: "shogi (Japanese chess)", bn: "শোগি (জাপানি দাবা)" },
  { id: 904, lesson: 14, kanji: "スイカ", furigana: "スイカ", romaji: "suika", en: "watermelon", bn: "তরমুজ" },
  { id: 905, lesson: 14, kanji: "（お）赤飯", furigana: "（お）せきはん", romaji: "(o)sekihan", en: "festive red rice", bn: "সেকিহান (উৎসবের লাল ভাত)" },
  { id: 906, lesson: 14, kanji: "先祖", furigana: "せんぞ", romaji: "senzo", en: "ancestor", bn: "পূর্বপুরুষ" },
  { id: 907, lesson: 14, kanji: "山車", furigana: "だし", romaji: "dashi", en: "parade float", bn: "উৎসবের সুসজ্জিত গাড়ি" },
  { id: 908, lesson: 14, kanji: "チェス", furigana: "チェス", romaji: "chesu", en: "chess", bn: "দাবা" },
  { id: 909, lesson: 14, kanji: "テコンドー", furigana: "テコンドー", romaji: "tekondoo", en: "tae kwon do", bn: "তায়কোয়ান্দো" },
  { id: 910, lesson: 14, kanji: "年", furigana: "とし", romaji: "toshi", en: "age, year", bn: "বয়স / বছর" },
  { id: 911, lesson: 14, kanji: "新しい年", furigana: "あたらしいとし", romaji: "atarashii toshi", en: "a new year, the coming year", bn: "নতুন বছর" },
  { id: 912, lesson: 14, kanji: "パクさんの年", furigana: "パクさんのとし", romaji: "paku san no toshi", en: "Pak's age", bn: "পাক সাহেবের বয়স" },
  { id: 913, lesson: 14, kanji: "布", furigana: "ぬの", romaji: "nuno", en: "fabric", bn: "কাপড়" },
  { id: 914, lesson: 14, kanji: "年賀状", furigana: "ねんがじょう", romaji: "nengajou", en: "New Year's greeting card", bn: "নববর্ষের শুভেচ্ছা কার্ড" },
  { id: 915, lesson: 14, kanji: "はがき", furigana: "はがき", romaji: "hagaki", en: "postcard", bn: "পোস্টকার্ড" },
  { id: 916, lesson: 14, kanji: "風呂敷", furigana: "ふろしき", romaji: "furoshiki", en: "cloth for wrapping things", bn: "ফুরোশিকি (মোড়ক কাপড়)" },
  { id: 917, lesson: 14, kanji: "招き猫", furigana: "まねきねこ", romaji: "manekineko", en: "welcoming cat statue", bn: "মানেকিনেকো (সৌভাগ্যের বিড়াল)" },
  { id: 918, lesson: 14, kanji: "豆", furigana: "まめ", romaji: "mame", en: "bean", bn: "শিম / মটরশুঁটি" },
  { id: 919, lesson: 14, kanji: "ミカン", furigana: "ミカン", romaji: "mikan", en: "tangerine", bn: "কমলালেবু" },
  { id: 920, lesson: 14, kanji: "焼き鳥", furigana: "やきとり", romaji: "yakitori", en: "yakitori (grilled chicken)", bn: "ইয়াকিতোরি (চিকেন শিক কাবাব)" },
  { id: 921, lesson: 14, kanji: "ユズ", furigana: "ユズ", romaji: "yuzu", en: "yuzu (citrus)", bn: "ইউজু লেবু" },
  { id: 922, lesson: 14, kanji: "夢", furigana: "ゆめ", romaji: "yume", en: "dream (during sleep)", bn: "স্বপ্ন" },
  { id: 923, lesson: 14, kanji: "昨日、悪い夢を見た", furigana: "きのう、わるいゆめをみた", romaji: "kinou, warui yume o mita", en: "\"I had a bad dream yesterday.\"", bn: "গতকাল একটি খারাপ স্বপ্ন দেখেছি" },
  { id: 924, lesson: 14, kanji: "ランドセル", furigana: "ランドセル", romaji: "randoseru", en: "elementary school backpack", bn: "প্রাথমিক স্কুলের বিশেষ ব্যাগ" },
  { id: 925, lesson: 14, kanji: "～県（長崎県）", furigana: "～けん（ながさきけん）", romaji: "~ken (nagasakiken)", en: "~ prefecture (Nagasaki)", bn: "প্রশাসনিক জেলা (নাগাসাকি)" },
  { id: 926, lesson: 14, kanji: "祈る", furigana: "いのる", romaji: "inoru", en: "pray", bn: "প্রার্থনা করা" },
  { id: 927, lesson: 14, kanji: "祝う", furigana: "いわう", romaji: "iwau", en: "celebrate, congratulate", bn: "উদযাপন করা" },
  { id: 928, lesson: 14, kanji: "踊る", furigana: "おどる", romaji: "odoru", en: "dance", bn: "নাচ করা" },
  { id: 929, lesson: 14, kanji: "飾る", furigana: "かざる", romaji: "kazaru", en: "decorate, put up decoration", bn: "সাজানো" },
  { id: 930, lesson: 14, kanji: "包む", furigana: "つつむ", romaji: "tsutsumu", en: "wrap up, roll up", bn: "মোড়ানো" },
  { id: 931, lesson: 14, kanji: "お祝い・する", furigana: "おいわいする", romaji: "oiwai suru", en: "celebrate", bn: "শুভেচ্ছা বা উদযাপন করা" },
  { id: 932, lesson: 14, kanji: "感謝・する", furigana: "かんしゃする", romaji: "kansha suru", en: "thank, express appreciation", bn: "কৃতজ্ঞতা প্রকাশ করা" },
  { id: 933, lesson: 14, kanji: "成長・する", furigana: "せいちょうする", romaji: "seichou suru", en: "grow, develop", bn: "বেড়ে ওঠা" },
  { id: 934, lesson: 14, kanji: "長生き・する", furigana: "ながいきする", romaji: "nagaiki suru", en: "live a long life", bn: "দীর্ঘায়ু হওয়া" },
  { id: 935, lesson: 14, kanji: "夏バテ・する", furigana: "なつばてする", romaji: "natsubate suru", en: "suffer from the summer heat", bn: "গ্রীষ্মের ক্লান্তিতে ভোগা" },
  { id: 936, lesson: 14, kanji: "特別（な）", furigana: "とくべつ（な）", romaji: "tokubetsu (na)", en: "special", bn: "বিশেষ" },
  { id: 937, lesson: 14, kanji: "イヤホン", furigana: "イヤホン", romaji: "iyahon", en: "earphones", bn: "ইয়ারফোন" },
  { id: 938, lesson: 14, kanji: "置物", furigana: "おきもの", romaji: "okimono", en: "ornament", bn: "সাজানোর শো-পিস" },
  { id: 939, lesson: 14, kanji: "火事", furigana: "かじ", romaji: "kaji", en: "fire", bn: "অগ্নিকাণ্ড" },
  { id: 940, lesson: 14, kanji: "カメ", furigana: "カメ", romaji: "kame", en: "turtle, tortoise", bn: "কচ্ছপ" },
  { id: 941, lesson: 14, kanji: "菊", furigana: "きく", romaji: "kiku", en: "chrysanthemum", bn: "চন্দ্রমল্লিকা" },
  { id: 942, lesson: 14, kanji: "くし", furigana: "くし", romaji: "kushi", en: "hair comb", bn: "চিরুনি" },
  { id: 943, lesson: 14, kanji: "5円玉", furigana: "ごえんだま", romaji: "goendama", en: "five yen coin", bn: "৫ ইয়েনের কয়েন" },
  { id: 944, lesson: 14, kanji: "食器", furigana: "しょっき", romaji: "shokki", en: "dishes, tableware", bn: "থালাবাসন" },
  { id: 945, lesson: 14, kanji: "シンボル", furigana: "シンボル", romaji: "shinboru", en: "symbol", bn: "প্রতীক" },
  { id: 946, lesson: 14, kanji: "ストーブ", furigana: "ストーブ", romaji: "sutoobu", en: "stove, space heater", bn: "হিটার" },
  { id: 947, lesson: 14, kanji: "（お）葬式", furigana: "（お）そうしき", romaji: "(o)soushiki", en: "funeral ceremony", bn: "অন্ত্যেষ্টিক্রিয়া" },
  { id: 948, lesson: 14, kanji: "涙", furigana: "なみだ", romaji: "namida", en: "tears", bn: "চোখের জল" },
  { id: 949, lesson: 14, kanji: "ハンカチ", furigana: "ハンカチ", romaji: "hankachi", en: "handkerchief", bn: "রুমাল" },
  { id: 950, lesson: 14, kanji: "日傘", furigana: "ひがさ", romaji: "higasa", en: "parasol, sunshade", bn: "রোদের ছাতা" },
  { id: 951, lesson: 14, kanji: "（お）見舞い", furigana: "（お）みまい", romaji: "(o)mimai", en: "visit a sick person", bn: "রোগী দেখতে যাওয়া" },
  { id: 952, lesson: 14, kanji: "みんな", furigana: "みんな", romaji: "minna", en: "everyone", bn: "সবাই" },
  { id: 953, lesson: 14, kanji: "ライター", furigana: "ライター", romaji: "raitaa", en: "lighter", bn: "লাইটার" },
  { id: 954, lesson: 14, kanji: "～祝い（結婚祝い）", furigana: "～いわい（けっこんいわい）", romaji: "~iwai (kekkon'iwai)", en: "celebration gift (wedding present)", bn: "উপহার (বিয়ের উপহার)" },
  { id: 955, lesson: 14, kanji: "贈る", furigana: "おくる", romaji: "okuru", en: "give a gift", bn: "উপহার দেওয়া" },
  { id: 956, lesson: 14, kanji: "増える", furigana: "ふえる", romaji: "fueru", en: "increase, grow in number", bn: "বৃদ্ধি পাওয়া" },
  { id: 957, lesson: 14, kanji: "発音・する", furigana: "はつおんする", romaji: "hatsuon suru", en: "pronounce", bn: "উচ্চারণ করা" },
  { id: 958, lesson: 14, kanji: "連想・する", furigana: "れんそうする", romaji: "rensou suru", en: "make an association of ideas", bn: "স্মরণে আনা / সংযোগ খোঁজা" },
  { id: 959, lesson: 14, kanji: "恥ずかしい", furigana: "はずかしい", romaji: "hazukashii", en: "embarrassing", bn: "লজ্জাজনক" },
  { id: 960, lesson: 14, kanji: "鬼", furigana: "おに", romaji: "oni", en: "demon, devil", bn: "রাক্ষস / দৈত্য" },
  { id: 961, lesson: 14, kanji: "提灯", furigana: "ちょうちん", romaji: "chouchin", en: "paper lantern", bn: "কাগজের লণ্ঠন" },
  { id: 962, lesson: 14, kanji: "ハロウィン", furigana: "ハロウィン", romaji: "harowin", en: "Halloween", bn: "হ্যালোউইন" },
  { id: 963, lesson: 14, kanji: "そういう", furigana: "そういう", romaji: "souiu", en: "that kind of ~, such", bn: "সেই ধরনের" },

  // LESSON 15: 気になるニュース (News of Interest)
  { id: 964, lesson: 15, kanji: "自信", furigana: "じしん", romaji: "jishin", en: "confidence", bn: "আত্মবিশ্বাস" },
  { id: 965, lesson: 15, kanji: "知り合い", furigana: "しりあい", romaji: "shiriai", en: "acquaintance", bn: "পরিচিত ব্যক্তি" },
  { id: 966, lesson: 15, kanji: "大成功", furigana: "だいせいこう", romaji: "daiseikou", en: "great success", bn: "বিশাল সাফল্য" },
  { id: 967, lesson: 15, kanji: "取り組む", furigana: "とりくむ", romaji: "torikumu", en: "deal with, engage in, work on", bn: "কাজে মনোনিবেশ করা" },
  { id: 968, lesson: 15, kanji: "積極的（な）", furigana: "せっきょくてき（な）", romaji: "sekkyokuteki (na)", en: "proactive, positive", bn: "ইতিবাচক ও উদ্যোগী" },
  { id: 969, lesson: 15, kanji: "大雨", furigana: "おおあめ", romaji: "ooame", en: "heavy rain", bn: "ভারী বৃষ্টিপাত" },
  { id: 970, lesson: 15, kanji: "英会話", furigana: "えいかいわ", romaji: "eikaiwa", en: "English conversation", bn: "ইংরেজি কথোপকথন" },
  { id: 971, lesson: 15, kanji: "回数", furigana: "かいすう", romaji: "kaisuu", en: "number of times", bn: "সংখ্যা / বার" },
  { id: 972, lesson: 15, kanji: "グラフ", furigana: "グラフ", romaji: "gurafu", en: "graph", bn: "গ্রাফ / লেখচিত্র" },
  { id: 973, lesson: 15, kanji: "グループ", furigana: "グループ", romaji: "guruupu", en: "group", bn: "দল / গ্রুপ" },
  { id: 974, lesson: 15, kanji: "原因", furigana: "げんいん", romaji: "gen'in", en: "cause", bn: "কারণ" },
  { id: 975, lesson: 15, kanji: "事件", furigana: "じけん", romaji: "jiken", en: "incident, case, event", bn: "ঘটনা / মামলা" },
  { id: 976, lesson: 15, kanji: "事情", furigana: "じじょう", romaji: "jijou", en: "situation, circumstances", bn: "পরিস্থিতি / অবস্থা" },
  { id: 977, lesson: 15, kanji: "食料品", furigana: "しょくりょうひん", romaji: "shokuryouhin", en: "food items", bn: "খাদ্যসামগ্রী" },
  { id: 978, lesson: 15, kanji: "女性", furigana: "じょせい", romaji: "josei", en: "female", bn: "নারী / মহিলা" },
  { id: 979, lesson: 15, kanji: "男性", furigana: "だんせい", romaji: "dansei", en: "male", bn: "পুরুষ" },
  { id: 980, lesson: 15, kanji: "地球", furigana: "ちきゅう", romaji: "chikyuu", en: "the Earth", bn: "পৃথিবী গ্রহ" },
  { id: 981, lesson: 15, kanji: "テーマ", furigana: "テーマ", romaji: "teema", en: "theme, topic, subject matter", bn: "মূল প্রতিপাদ্য / বিষয়" },
  { id: 982, lesson: 15, kanji: "貿易", furigana: "ぼうえき", romaji: "boueki", en: "foreign trade", bn: "বৈদেশিক বাণিজ্য" },
  { id: 983, lesson: 15, kanji: "問題", furigana: "もんだい", romaji: "mondai", en: "problem, issue", bn: "সমস্যা / প্রশ্ন" },
  { id: 984, lesson: 15, kanji: "洋服", furigana: "ようふく", romaji: "youfuku", en: "Western-style clothing", bn: "পশ্চিমা পোশাক" },
  { id: 985, lesson: 15, kanji: "レコード", furigana: "レコード", romaji: "rekoodo", en: "record", bn: "রেকর্ড" },
  { id: 986, lesson: 15, kanji: "～化（温暖化）", furigana: "～か（おんだんか）", romaji: "~ka (ondanka)", en: "change into ~ (global warming)", bn: "-করণ (উষ্ণায়ন)" },
  { id: 987, lesson: 15, kanji: "～倍", furigana: "～ばい", romaji: "~bai", en: "by ~ times", bn: "গুণ" },
  { id: 988, lesson: 15, kanji: "飼う", furigana: "かう", romaji: "kau", en: "raise (pet or animal)", bn: "পশু-পাখি পোষা" },
  { id: 989, lesson: 15, kanji: "下がる", furigana: "さがる", romaji: "sagaru", en: "fall, drop", bn: "কমে যাওয়া / নামা" },
  { id: 990, lesson: 15, kanji: "値段が下がる", furigana: "ねだんがさがる", romaji: "nedan ga sagaru", en: "the price drops", bn: "দাম কমা" },
  { id: 991, lesson: 15, kanji: "咲く", furigana: "さく", romaji: "saku", en: "blossom, bloom", bn: "ফোটা / প্রস্ফুটিত হওয়া" },
  { id: 992, lesson: 15, kanji: "過ごす", furigana: "すごす", romaji: "sugosu", en: "spend time", bn: "সময় কাটানো" },
  { id: 993, lesson: 15, kanji: "植える", furigana: "うえる", romaji: "ueru", en: "to plant", bn: "গাছ লাগানো" },
  { id: 994, lesson: 15, kanji: "比べる", furigana: "くらべる", romaji: "kuraberu", en: "compare", bn: "তুলনা করা" },
  { id: 995, lesson: 15, kanji: "アンケート・する", furigana: "アンケートする", romaji: "ankeeto suru", en: "take a survey", bn: "জরিপ করা" },
  { id: 996, lesson: 15, kanji: "お願い・する", furigana: "おねがいする", romaji: "onegai suru", en: "ask, beg (politely)", bn: "বিনীত অনুরোধ করা" },
  { id: 997, lesson: 15, kanji: "増加・する", furigana: "ぞうかする", romaji: "zouka suru", en: "increase", bn: "বৃদ্ধি পাওয়া" },
  { id: 998, lesson: 15, kanji: "輸入・する", furigana: "ゆにゅうする", romaji: "yunyuu suru", en: "import", bn: "আমদানি করা" },
  { id: 999, lesson: 15, kanji: "来日・する", furigana: "らいにちする", romaji: "rainichi suru", en: "visit Japan", bn: "জাপানে আসা" },
  { id: 1000, lesson: 15, kanji: "流行・する", furigana: "りゅうこうする", romaji: "ryuukou suru", en: "become fashionable, popular", bn: "প্রচলিত বা জনপ্রিয় হওয়া" },
  { id: 1001, lesson: 15, kanji: "気になる", furigana: "きになる", romaji: "ki ni naru", en: "worry about, be interested in", bn: "মাথায় ঘোরা / ভাবনায় আসা" },
  { id: 1002, lesson: 15, kanji: "汚い", furigana: "きたない", romaji: "kitanai", en: "dirty", bn: "নোংরা / অপরিচ্ছন্ন" },
  { id: 1003, lesson: 15, kanji: "温暖（な）", furigana: "おんだん（な）", romaji: "ondan (na)", en: "warm, mild", bn: "উষ্ণ / নাতিশীতোষ্ণ" },
  { id: 1004, lesson: 15, kanji: "直接", furigana: "ちょくせつ", romaji: "chokusetsu", en: "direct, directly", bn: "সরাসরি" },
  { id: 1005, lesson: 15, kanji: "ほとんど", furigana: "ほとんど", romaji: "hotondo", en: "hardly, almost", bn: "প্রায় সম্পূর্ণ" },
  { id: 1006, lesson: 15, kanji: "インフルエンザ", furigana: "インフルエンザ", romaji: "infuruenza", en: "flu, influenza", bn: "ইনফ্লুয়েঞ্জা জ্বর" },
  { id: 1007, lesson: 15, kanji: "円高", furigana: "えんだか", romaji: "endaka", en: "strong yen, yen appreciation", bn: "ইয়েনের দাম বৃদ্ধি" },
  { id: 1008, lesson: 15, kanji: "円安", furigana: "えんやす", romaji: "en'yasu", en: "weak yen, yen depreciation", bn: "ইয়েনের মান কমে যাওয়া" },
  { id: 1009, lesson: 15, kanji: "気温", furigana: "きおん", romaji: "kion", en: "air temperature", bn: "বাতাসের তাপমাত্রা" },
  { id: 1010, lesson: 15, kanji: "立入禁止", furigana: "たちいりきんし", romaji: "tachiirikinshi", en: "entry prohibited", bn: "প্রবেশ নিষেধ" },
  { id: 1011, lesson: 15, kanji: "南極", furigana: "なんきょく", romaji: "nankyoku", en: "south pole", bn: "দক্ষিণ মেরু" },
  { id: 1012, lesson: 15, kanji: "北極", furigana: "ほっきょく", romaji: "hokkyoku", en: "north pole", bn: "উত্তর মেরু" },
  { id: 1013, lesson: 15, kanji: "ポスター", furigana: "ポスター", romaji: "posutaa", en: "poster", bn: "পোস্টার" },
  { id: 1014, lesson: 15, kanji: "進む", furigana: "すすむ", romaji: "susumu", en: "move forward, advance", bn: "অগ্রসর হওয়া" },
  { id: 1015, lesson: 15, kanji: "研究が進む", furigana: "けんきゅうがすすむ", romaji: "kenkyuu ga susumu", en: "\"The research moves forward.\"", bn: "গবেষণা এগিয়ে চলা" },
  { id: 1016, lesson: 15, kanji: "減る", furigana: "へる", romaji: "heru", en: "decrease, reduce in number", bn: "কমে যাওয়া / হ্রাস পাওয়া" },
  { id: 1017, lesson: 15, kanji: "溶ける", furigana: "とける", romaji: "tokeru", en: "melt", bn: "গলে যাওয়া" },
  { id: 1018, lesson: 15, kanji: "欠席・する", furigana: "けっせきする", romaji: "kesseki suru", en: "be absent, not attend", bn: "অনুপস্থিত থাকা" },
  { id: 1019, lesson: 15, kanji: "輸出・する", furigana: "ゆしゅつする", romaji: "yushutsu suru", en: "export", bn: "রপ্তানি করা" },
  { id: 1020, lesson: 15, kanji: "危険（な）", furigana: "きけん（な）", romaji: "kiken (na)", en: "dangerous, hazardous", bn: "বিপজ্জনক" },
  { id: 1021, lesson: 15, kanji: "大変", furigana: "たいへん", romaji: "taihen", en: "very, serious", bn: "খুব / কঠিন" },
  { id: 1022, lesson: 15, kanji: "どんどん", furigana: "どんどん", romaji: "dondon", en: "more and more, rapidly", bn: "ক্রমান্বয়ে / দ্রুত" },
  { id: 1023, lesson: 15, kanji: "しかし", furigana: "しかし", romaji: "shikashi", en: "however, but", bn: "কিন্তু / তবে" },
  { id: 1024, lesson: 15, kanji: "～によると", furigana: "～によると", romaji: "~ ni yoru to", en: "according to ~", bn: "অনুযায়ী / মতে" },
  { id: 1025, lesson: 15, kanji: "行き先", furigana: "いきさき", romaji: "ikisaki", en: "destination", bn: "গন্তব্য" },
  { id: 1026, lesson: 15, kanji: "結果", furigana: "けっか", romaji: "kekka", en: "results", bn: "ফলাফল" },
  { id: 1027, lesson: 15, kanji: "サイト", furigana: "サイト", romaji: "saito", en: "website", bn: "ওয়েবসাইট" },
  { id: 1028, lesson: 15, kanji: "全体", furigana: "ぜんたい", romaji: "zentai", en: "overall, whole", bn: "সামগ্রিক / সম্পূর্ণ" },
  { id: 1029, lesson: 15, kanji: "僕", furigana: "ぼく", romaji: "boku", en: "I, me (informal male)", bn: "আমি (ছেলেরা বলে)" },
  { id: 1030, lesson: 15, kanji: "前", furigana: "まえ", romaji: "mae", en: "before", bn: "পূর্বে / আগে" },
  { id: 1031, lesson: 15, kanji: "気楽（な）", furigana: "きらく（な）", romaji: "kiraku (na)", en: "carefree", bn: "ভারমুক্ত / নিশ্চিন্ত" },
  { id: 1032, lesson: 15, kanji: "不安（な）", furigana: "ふあん（な）", romaji: "fuan (na)", en: "unease, anxiety", bn: "উদ্বেগ / দুশ্চিন্তা" },
  { id: 1033, lesson: 15, kanji: "約～", furigana: "やく～", romaji: "yaku~", en: "about, approximately ~", bn: "প্রায় / আনুমানিক" }
];

// Combine all parts into a single master array
window.VOCABULARY = [
  ...(window.VOCABULARY_PART1 || []),
  ...(window.VOCABULARY_PART2 || []),
  ...(window.VOCABULARY_PART3 || [])
];
